type: object
title: ProductInquiryListResponse
description: Header once with an array of product inquiry bodies.
required:
  - header
  - body
properties:
  header:
    type: object
    required:
      - resultCode
      - resultMessage
    properties:
      resultCode:
        type: string
        example: "0000"
      resultMessage:
        type: string
        example: Successful Operation
  body:
    type: array
    maxItems: 1000
    items:
      $ref: './ProductInquiryBody.yaml'
