type: object
title: ProductListRequest
description: Request to fetch product inquiry data.
required: [header, body]
properties:
  header:
    $ref: './CommonRequestHeader.yaml'
  body:
    $ref: './ProductListRequestBody.yaml'
additionalProperties: false
