# components/schemas/ProductImage.yaml
type: object
description: Product image reference
required:
  - channelImageId
properties:
  channelImageId:
    type: string
    description: channel needs to return image ID
    example: IMG_123456789
