# components/schemas/ProductCategory.yaml
type: object
description: GGT product category
required:
  - code
properties:
  code:
    type: string
    description: GGT category code
    enum:
      - ATTRACTION_TICKET
      - SHOW_EVENT_TICKET
      - MULTI_ATTRACTION_TICKETS
      - CRUISE_TICKET
      - DAY_TOUR
      - HELICOPTER_TOURS
      - HOT_AIR_BALLOON_RIDES
      - PARACHUTING
      - JUNGLE_ZIPLINING
      - DIVING
      - ROCK_CLIMBING
      - WI_FI
      - SPEEDBOATING
      - SEAPLANE_RIDES
      - SAILING
      - TOUR_GUIDE
      - BOAT_SPEEDBOAT_TICKETS
      - AIRPORT_TRANSFERS
      - POINT_TO_POINT_TRANSFER
      - MEALS
      - GOLF
      - CYCLING
      - OFF_ROADING
      - CLASSES_COURSES
      - SKIING
      - PARAGLIDING
      - CANOEING_KAYAKING
      - SPA_TREATMENTS
      - TRAVEL_PHOTO_SHOOTS
      - SIGHTSEEING_BUS_RIDES
      - SOUVENIRS
    example: ATTRACTION_TICKET
