// Package shallow provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package shallow

import (
	"encoding/json"
	"time"

	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ResourcePriceSyncJSONBodyBodyDateType.
const (
	ResourcePriceSyncJSONBodyBodyDateTypeDATENOTREQUIRED ResourcePriceSyncJSONBodyBodyDateType = "DATE_NOT_REQUIRED"
	ResourcePriceSyncJSONBodyBodyDateTypeDATEREQUIRED    ResourcePriceSyncJSONBodyBodyDateType = "DATE_REQUIRED"
)

// Defines values for ResourceInventorySyncJSONBodyBodyDateType.
const (
	ResourceInventorySyncJSONBodyBodyDateTypeDATENOTREQUIRED ResourceInventorySyncJSONBodyBodyDateType = "DATE_NOT_REQUIRED"
	ResourceInventorySyncJSONBodyBodyDateTypeDATEREQUIRED    ResourceInventorySyncJSONBodyBodyDateType = "DATE_REQUIRED"
)

// Defines values for SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType.
const (
	SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitTypeCustomized SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType = "Customized"
	SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitTypeMultiDate  SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType = "Multi_Date"
	SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitTypeSingleDate SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType = "Single_Date"
	SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitTypeUnlimited  SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType = "Unlimited"
)

// Defines values for SyncProductJSONBodyBookingSettingsBookingTypeDateType.
const (
	DATENOTREQUIRED SyncProductJSONBodyBookingSettingsBookingTypeDateType = "DATE_NOT_REQUIRED"
	DATEREQUIRED    SyncProductJSONBodyBookingSettingsBookingTypeDateType = "DATE_REQUIRED"
)

// Defines values for SyncProductJSONBodyCancellationPolicyConfirmationTime.
const (
	N16 SyncProductJSONBodyCancellationPolicyConfirmationTime = 16
	N24 SyncProductJSONBodyCancellationPolicyConfirmationTime = 24
	N8  SyncProductJSONBodyCancellationPolicyConfirmationTime = 8
)

// Defines values for SyncProductJSONBodyCancellationPolicyRateListUnit.
const (
	PERCENTAGE SyncProductJSONBodyCancellationPolicyRateListUnit = "PERCENTAGE"
)

// Defines values for SyncProductJSONBodyCancellationPolicyType.
const (
	ByVisitDate    SyncProductJSONBodyCancellationPolicyType = "By_Visit_Date"
	FreeCancel     SyncProductJSONBodyCancellationPolicyType = "Free_Cancel"
	NonCancellable SyncProductJSONBodyCancellationPolicyType = "Non_Cancellable"
)

// Defines values for SyncProductJSONBodyCategoryCode.
const (
	AIRPORTTRANSFERS       SyncProductJSONBodyCategoryCode = "AIRPORT_TRANSFERS"
	ATTRACTIONTICKET       SyncProductJSONBodyCategoryCode = "ATTRACTION_TICKET"
	BOATSPEEDBOATTICKETS   SyncProductJSONBodyCategoryCode = "BOAT_SPEEDBOAT_TICKETS"
	CANOEINGKAYAKING       SyncProductJSONBodyCategoryCode = "CANOEING_KAYAKING"
	CLASSESCOURSES         SyncProductJSONBodyCategoryCode = "CLASSES_COURSES"
	CRUISETICKET           SyncProductJSONBodyCategoryCode = "CRUISE_TICKET"
	CYCLING                SyncProductJSONBodyCategoryCode = "CYCLING"
	DAYTOUR                SyncProductJSONBodyCategoryCode = "DAY_TOUR"
	DIVING                 SyncProductJSONBodyCategoryCode = "DIVING"
	GOLF                   SyncProductJSONBodyCategoryCode = "GOLF"
	HELICOPTERTOURS        SyncProductJSONBodyCategoryCode = "HELICOPTER_TOURS"
	HOTAIRBALLOONRIDES     SyncProductJSONBodyCategoryCode = "HOT_AIR_BALLOON_RIDES"
	JUNGLEZIPLINING        SyncProductJSONBodyCategoryCode = "JUNGLE_ZIPLINING"
	MEALS                  SyncProductJSONBodyCategoryCode = "MEALS"
	MULTIATTRACTIONTICKETS SyncProductJSONBodyCategoryCode = "MULTI_ATTRACTION_TICKETS"
	OFFROADING             SyncProductJSONBodyCategoryCode = "OFF_ROADING"
	PARACHUTING            SyncProductJSONBodyCategoryCode = "PARACHUTING"
	PARAGLIDING            SyncProductJSONBodyCategoryCode = "PARAGLIDING"
	POINTTOPOINTTRANSFER   SyncProductJSONBodyCategoryCode = "POINT_TO_POINT_TRANSFER"
	ROCKCLIMBING           SyncProductJSONBodyCategoryCode = "ROCK_CLIMBING"
	SAILING                SyncProductJSONBodyCategoryCode = "SAILING"
	SEAPLANERIDES          SyncProductJSONBodyCategoryCode = "SEAPLANE_RIDES"
	SHOWEVENTTICKET        SyncProductJSONBodyCategoryCode = "SHOW_EVENT_TICKET"
	SIGHTSEEINGBUSRIDES    SyncProductJSONBodyCategoryCode = "SIGHTSEEING_BUS_RIDES"
	SKIING                 SyncProductJSONBodyCategoryCode = "SKIING"
	SOUVENIRS              SyncProductJSONBodyCategoryCode = "SOUVENIRS"
	SPATREATMENTS          SyncProductJSONBodyCategoryCode = "SPA_TREATMENTS"
	SPEEDBOATING           SyncProductJSONBodyCategoryCode = "SPEEDBOATING"
	TOURGUIDE              SyncProductJSONBodyCategoryCode = "TOUR_GUIDE"
	TRAVELPHOTOSHOOTS      SyncProductJSONBodyCategoryCode = "TRAVEL_PHOTO_SHOOTS"
	WIFI                   SyncProductJSONBodyCategoryCode = "WI_FI"
)

// Defines values for SyncProductJSONBodyDurationUnit.
const (
	SyncProductJSONBodyDurationUnitDay    SyncProductJSONBodyDurationUnit = "Day"
	SyncProductJSONBodyDurationUnitHour   SyncProductJSONBodyDurationUnit = "Hour"
	SyncProductJSONBodyDurationUnitMinute SyncProductJSONBodyDurationUnit = "Minute"
)

// Defines values for SyncProductJSONBodyGuestInformationCode.
const (
	BIRTHDATE  SyncProductJSONBodyGuestInformationCode = "BIRTH_DATE"
	COUNTRY    SyncProductJSONBodyGuestInformationCode = "COUNTRY"
	GUESTNAME  SyncProductJSONBodyGuestInformationCode = "GUEST_NAME"
	PassportNo SyncProductJSONBodyGuestInformationCode = "PassportNo"
)

// Defines values for SyncProductJSONBodyGuestInformationType.
const (
	PERORDER  SyncProductJSONBodyGuestInformationType = "PER_ORDER"
	PERPERSON SyncProductJSONBodyGuestInformationType = "PER_PERSON"
)

// Defines values for SyncProductJSONBodyItineraryDurationUnit.
const (
	SyncProductJSONBodyItineraryDurationUnitDay    SyncProductJSONBodyItineraryDurationUnit = "Day"
	SyncProductJSONBodyItineraryDurationUnitHour   SyncProductJSONBodyItineraryDurationUnit = "Hour"
	SyncProductJSONBodyItineraryDurationUnitMinute SyncProductJSONBodyItineraryDurationUnit = "Minute"
)

// Defines values for SyncProductJSONBodyItineraryEndEndType.
const (
	DropOffEveryone SyncProductJSONBodyItineraryEndEndType = "Drop_Off_Everyone"
	EndAfterReturn  SyncProductJSONBodyItineraryEndEndType = "End_After_Return"
	EndOnTheSpot    SyncProductJSONBodyItineraryEndEndType = "End_on_the_Spot"
)

// Defines values for SyncProductJSONBodyItineraryStartStartType.
const (
	SyncProductJSONBodyItineraryStartStartTypeMeetAtStartPoint SyncProductJSONBodyItineraryStartStartType = "Meet_at_Start_Point"
	SyncProductJSONBodyItineraryStartStartTypePickupEveryone   SyncProductJSONBodyItineraryStartStartType = "Pickup_Everyone"
)

// Defines values for SyncProductJSONBodyOptionOptionCode.
const (
	Option   SyncProductJSONBodyOptionOptionCode = "Option"
	TimeSlot SyncProductJSONBodyOptionOptionCode = "Time_Slot"
)

// Defines values for SyncProductJSONBodyPaymentConfirmationTime.
const (
	N10  SyncProductJSONBodyPaymentConfirmationTime = 10
	N120 SyncProductJSONBodyPaymentConfirmationTime = 120
	N15  SyncProductJSONBodyPaymentConfirmationTime = 15
	N30  SyncProductJSONBodyPaymentConfirmationTime = 30
	N40  SyncProductJSONBodyPaymentConfirmationTime = 40
	N5   SyncProductJSONBodyPaymentConfirmationTime = 5
	N60  SyncProductJSONBodyPaymentConfirmationTime = 60
)

// Defines values for SyncProductJSONBodyPrimaryLanguage.
const (
	SyncProductJSONBodyPrimaryLanguageEnUS SyncProductJSONBodyPrimaryLanguage = "en-US"
	SyncProductJSONBodyPrimaryLanguageJaJP SyncProductJSONBodyPrimaryLanguage = "ja-JP"
	SyncProductJSONBodyPrimaryLanguageKoKR SyncProductJSONBodyPrimaryLanguage = "ko-KR"
	SyncProductJSONBodyPrimaryLanguageThTH SyncProductJSONBodyPrimaryLanguage = "th-TH"
	SyncProductJSONBodyPrimaryLanguageZhCN SyncProductJSONBodyPrimaryLanguage = "zh-CN"
	SyncProductJSONBodyPrimaryLanguageZhHK SyncProductJSONBodyPrimaryLanguage = "zh-HK"
)

// Defines values for SyncProductJSONBodyRedemptionInfoRedemptionType.
const (
	SyncProductJSONBodyRedemptionInfoRedemptionTypeDirectEntry        SyncProductJSONBodyRedemptionInfoRedemptionType = "Direct_Entry"
	SyncProductJSONBodyRedemptionInfoRedemptionTypeMeetAtStartPoint   SyncProductJSONBodyRedemptionInfoRedemptionType = "Meet_at_Start_Point"
	SyncProductJSONBodyRedemptionInfoRedemptionTypeNeedTicketExchange SyncProductJSONBodyRedemptionInfoRedemptionType = "Need_Ticket_Exchange"
	SyncProductJSONBodyRedemptionInfoRedemptionTypePickUpEveryone     SyncProductJSONBodyRedemptionInfoRedemptionType = "Pick_Up_Everyone"
)

// Defines values for SyncProductJSONBodyServiceLanguageLanguageCode.
const (
	SyncProductJSONBodyServiceLanguageLanguageCodeDe    SyncProductJSONBodyServiceLanguageLanguageCode = "de"
	SyncProductJSONBodyServiceLanguageLanguageCodeEn    SyncProductJSONBodyServiceLanguageLanguageCode = "en"
	SyncProductJSONBodyServiceLanguageLanguageCodeEs    SyncProductJSONBodyServiceLanguageLanguageCode = "es"
	SyncProductJSONBodyServiceLanguageLanguageCodeFi    SyncProductJSONBodyServiceLanguageLanguageCode = "fi"
	SyncProductJSONBodyServiceLanguageLanguageCodeFr    SyncProductJSONBodyServiceLanguageLanguageCode = "fr"
	SyncProductJSONBodyServiceLanguageLanguageCodeId    SyncProductJSONBodyServiceLanguageLanguageCode = "id"
	SyncProductJSONBodyServiceLanguageLanguageCodeIt    SyncProductJSONBodyServiceLanguageLanguageCode = "it"
	SyncProductJSONBodyServiceLanguageLanguageCodeJa    SyncProductJSONBodyServiceLanguageLanguageCode = "ja"
	SyncProductJSONBodyServiceLanguageLanguageCodeKo    SyncProductJSONBodyServiceLanguageLanguageCode = "ko"
	SyncProductJSONBodyServiceLanguageLanguageCodeMs    SyncProductJSONBodyServiceLanguageLanguageCode = "ms"
	SyncProductJSONBodyServiceLanguageLanguageCodePt    SyncProductJSONBodyServiceLanguageLanguageCode = "pt"
	SyncProductJSONBodyServiceLanguageLanguageCodeRu    SyncProductJSONBodyServiceLanguageLanguageCode = "ru"
	SyncProductJSONBodyServiceLanguageLanguageCodeTh    SyncProductJSONBodyServiceLanguageLanguageCode = "th"
	SyncProductJSONBodyServiceLanguageLanguageCodeVi    SyncProductJSONBodyServiceLanguageLanguageCode = "vi"
	SyncProductJSONBodyServiceLanguageLanguageCodeZhCAN SyncProductJSONBodyServiceLanguageLanguageCode = "zh-CAN"
	SyncProductJSONBodyServiceLanguageLanguageCodeZhCN  SyncProductJSONBodyServiceLanguageLanguageCode = "zh-CN"
)

// Defines values for SyncProductJSONBodyStatus.
const (
	SyncProductJSONBodyStatusActive   SyncProductJSONBodyStatus = "active"
	SyncProductJSONBodyStatusInactive SyncProductJSONBodyStatus = "inactive"
)

// Defines values for SyncProductJSONBodyTicketInfoDeliveryMethods.
const (
	DIGITAL SyncProductJSONBodyTicketInfoDeliveryMethods = "DIGITAL"
	PRINT   SyncProductJSONBodyTicketInfoDeliveryMethods = "PRINT"
	VALIDID SyncProductJSONBodyTicketInfoDeliveryMethods = "VALID_ID"
)

// Defines values for SyncProductJSONBodyTicketTypeCode.
const (
	SyncProductJSONBodyTicketTypeCodeAdult      SyncProductJSONBodyTicketTypeCode = "Adult"
	SyncProductJSONBodyTicketTypeCodeChild      SyncProductJSONBodyTicketTypeCode = "Child"
	SyncProductJSONBodyTicketTypeCodeCustomized SyncProductJSONBodyTicketTypeCode = "Customized"
	SyncProductJSONBodyTicketTypeCodeInfant     SyncProductJSONBodyTicketTypeCode = "Infant"
	SyncProductJSONBodyTicketTypeCodeSenior     SyncProductJSONBodyTicketTypeCode = "Senior"
	SyncProductJSONBodyTicketTypeCodeStudent    SyncProductJSONBodyTicketTypeCode = "Student"
	SyncProductJSONBodyTicketTypeCodeTraveler   SyncProductJSONBodyTicketTypeCode = "Traveler"
	SyncProductJSONBodyTicketTypeCodeYouth      SyncProductJSONBodyTicketTypeCode = "Youth"
)

// Defines values for SyncPackageJSONBodyOptionListBookingQuestionsAnswerType.
const (
	FreeText        SyncPackageJSONBodyOptionListBookingQuestionsAnswerType = "Free_Text"
	SingleSelection SyncPackageJSONBodyOptionListBookingQuestionsAnswerType = "Single_Selection"
)

// Defines values for SyncPackageJSONBodyOptionListOptionStatus.
const (
	SyncPackageJSONBodyOptionListOptionStatusActive   SyncPackageJSONBodyOptionListOptionStatus = "active"
	SyncPackageJSONBodyOptionListOptionStatusInactive SyncPackageJSONBodyOptionListOptionStatus = "inactive"
)

// Defines values for SyncPackageJSONBodyOptionListUnitRestrictionsCompanionRequired.
const (
	NotRequired SyncPackageJSONBodyOptionListUnitRestrictionsCompanionRequired = "Not_Required"
	Required    SyncPackageJSONBodyOptionListUnitRestrictionsCompanionRequired = "Required"
)

// Defines values for SyncPackageJSONBodyOptionListUnitTicketTypeCode.
const (
	Adult      SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Adult"
	Child      SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Child"
	Customized SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Customized"
	Infant     SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Infant"
	Senior     SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Senior"
	Student    SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Student"
	Traveler   SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Traveler"
	Youth      SyncPackageJSONBodyOptionListUnitTicketTypeCode = "Youth"
)

// PayPreOrderConfirmJSONBody defines parameters for PayPreOrderConfirm.
type PayPreOrderConfirmJSONBody struct {
	// Body request body (AES-encrypted)
	Body struct {
		// ConfirmResultCode The return code of confirmation result.   See: Channel's standard interface codes (`0000` = success).
		ConfirmResultCode int `json:"confirmResultCode"`

		// ConfirmResultMessage Confirmation result detail (e.g. “Confirmation succeeded” or failure reason)
		ConfirmResultMessage string `json:"confirmResultMessage"`

		// Items Stock & passenger mapping per line item
		Items []struct {
			// Inventories Remaining stock nodes
			Inventories []struct {
				// Quantity Remaining quantity for that date
				Quantity int `json:"quantity"`

				// UseDate Valid date (`yyyy-MM-dd`)
				UseDate openapi_types.Date `json:"useDate"`
			} `json:"inventories"`

			// IsCredentialVouchers Whether passenger vouchers apply:   `1` = yes (must include `passengerVouchers`),   `0` = no
			IsCredentialVouchers int `json:"isCredentialVouchers"`

			// ItemId Order line item ID
			ItemId string `json:"itemId"`

			// PassengerVouchers Passenger-voucher relationships (when `isCredentialVouchers=1`)
			PassengerVouchers *[]struct {
				// PassengerId Passenger identifier
				PassengerId string `json:"passengerId"`

				// VoucherId Voucher number
				VoucherId string `json:"voucherId"`
			} `json:"passengerVouchers,omitempty"`
		} `json:"items"`

		// OrderExtendMessage Additional usage instructions
		OrderExtendMessage string `json:"orderExtendMessage"`

		// OtaOrderId Channel's order number
		OtaOrderId string `json:"otaOrderId"`

		// SequenceId GGT Batch Number (`yyyyMMdd` + 32-bit GUID without delimiters)
		SequenceId string `json:"sequenceId"`

		// SupplierOrderId GGT order number
		SupplierOrderId string `json:"supplierOrderId"`

		// VoucherSender Voucher sender:   `1` = Channel sends voucher;   `2` = Supplier sends voucher (mandatory if `voucherSender=2` at create time).
		VoucherSender int `json:"voucherSender"`

		// Vouchers Voucher collection (returned when `confirmResultCode=0000`)
		Vouchers []struct {
			// ItemId Order line item identifier
			ItemId *string `json:"itemId,omitempty"`

			// VoucherCode Ancillary code for types 3–8
			VoucherCode *string `json:"voucherCode,omitempty"`

			// VoucherData Data stream (base64 or original string) for QR/PDF/etc.
			VoucherData *string `json:"voucherData,omitempty"`

			// VoucherId Voucher number (required when credential vouchers apply)
			VoucherId *string `json:"voucherId,omitempty"`

			// VoucherSeatInfo Seat info (one-to-one with voucher), e.g. “Row 15, Seat 09”
			VoucherSeatInfo *string `json:"voucherSeatInfo,omitempty"`

			// VoucherType Voucher form:
			// 1 = Ordinary; 2 = Digital code; 3 = QR code; 4 = Image;
			// 5 = PDF; 6 = Link; 7 = Barcode128; 8 = Barcode417
			VoucherType int `json:"voucherType"`
		} `json:"vouchers"`
	} `json:"body"`

	// Header Standard GGT request header
	Header struct {
		// AccountId Channel's account, provided by GGT
		AccountId string `json:"accountId"`

		// RequestTime Request timestamp in `yyyy-MM-dd HH:mm:ss` format
		RequestTime time.Time `json:"requestTime"`

		// ServiceName Interface Name, one of CreatePreOrder, PayPreOrder, PayPreOrderConfirm, CancelPreOrder, CancelOrder, CancelOrderConfirm, OrderConsumedNotice, QueryOrder, QueryProduct, SupplierBalanceQuery based on APIs. For ResourcePriceSync API - DatePriceModify, For ResourceInventorySync API - DateInventoryModify
		ServiceName string `json:"serviceName"`

		// Sign Signature string for payload integrity, see signature algorithm
		Sign string `json:"sign"`

		// Version API version - 1.0
		Version string `json:"version"`
	} `json:"header"`
}

// CancelOrderConfirmJSONBody defines parameters for CancelOrderConfirm.
type CancelOrderConfirmJSONBody struct {
	// Body request body (AES-encrypted)
	Body struct {
		// ConfirmResultCode Confirmation return code.   See: The return code of Channel's interface (`0000` = success).
		ConfirmResultCode string `json:"confirmResultCode"`

		// ConfirmResultMessage Confirmation result information or failure reason
		ConfirmResultMessage string `json:"confirmResultMessage"`

		// Items Order line item node
		Items []struct {
			// ItemId Order line item number
			ItemId string `json:"itemId"`

			// Vouchers Canceled voucher node (required if a voucher was issued).
			// Note: if the order was consumed, vouchers cannot be reused.
			Vouchers *[]struct {
				// VoucherId Voucher number
				VoucherId string `json:"voucherId"`
			} `json:"vouchers,omitempty"`
		} `json:"items"`

		// OtaOrderId Channel order number
		OtaOrderId string `json:"otaOrderId"`

		// SequenceId Supplier’s Batch Number (`yyyyMMdd` + GUID)
		SequenceId string `json:"sequenceId"`

		// SupplierOrderId Supplier order number
		SupplierOrderId string `json:"supplierOrderId"`
	} `json:"body"`

	// Header Standard GGT request header
	Header struct {
		// AccountId Channel's account, provided by GGT
		AccountId string `json:"accountId"`

		// RequestTime Request timestamp in `yyyy-MM-dd HH:mm:ss` format
		RequestTime time.Time `json:"requestTime"`

		// ServiceName Interface Name, one of CreatePreOrder, PayPreOrder, PayPreOrderConfirm, CancelPreOrder, CancelOrder, CancelOrderConfirm, OrderConsumedNotice, QueryOrder, QueryProduct, SupplierBalanceQuery based on APIs. For ResourcePriceSync API - DatePriceModify, For ResourceInventorySync API - DateInventoryModify
		ServiceName string `json:"serviceName"`

		// Sign Signature string for payload integrity, see signature algorithm
		Sign string `json:"sign"`

		// Version API version - 1.0
		Version string `json:"version"`
	} `json:"header"`
}

// OrderConsumedNotificationJSONBody defines parameters for OrderConsumedNotification.
type OrderConsumedNotificationJSONBody struct {
	// Body request body (This field requires AES encryption during transmission)
	Body struct {
		// Items Array of order-line consumption nodes
		Items []struct {
			// Discount Preferential information node
			Discount *struct {
				// PolicyList Station-day discount policy list
				PolicyList *[]struct {
					// Date Offer date (`yyyy-MM-dd`)
					Date openapi_types.Date `json:"date"`

					// Quantity Preferential quantity
					Quantity int `json:"quantity"`
				} `json:"policyList,omitempty"`
			} `json:"discount,omitempty"`

			// ItemId Order line item number
			ItemId string `json:"itemId"`

			// LostAmount Actual amount of loss
			LostAmount *float32 `json:"lostAmount,omitempty"`

			// LostAmountCurrency Currency of loss amount (ISO code, e.g. `CNY`)
			LostAmountCurrency *string `json:"lostAmountCurrency,omitempty"`

			// Passengers Passengers corresponding to consumed orders (one per person).
			// Required if `useQuantity` > 0.
			Passengers *[]struct {
				// PassengerId Passenger number
				PassengerId string `json:"passengerId"`
			} `json:"passengers,omitempty"`

			// Quantity Total number of orders
			Quantity *int `json:"quantity,omitempty"`

			// Remark Remark information
			Remark *string `json:"remark,omitempty"`

			// UseEndDate Actual expiry date (`yyyy-MM-dd`) (same as start if one-day)
			UseEndDate *openapi_types.Date `json:"useEndDate,omitempty"`

			// UseQuantity Total number of orders that have been consumed (required if consumed)
			UseQuantity *int `json:"useQuantity,omitempty"`

			// UseStartDate Actual valid date (`yyyy-MM-dd`)
			UseStartDate *openapi_types.Date `json:"useStartDate,omitempty"`

			// Vouchers Consumed voucher nodes (required if vouchers were used).
			// If a voucher is consumed multiple times, report only the last consumption.
			Vouchers *[]struct {
				// VoucherId Voucher number
				VoucherId string `json:"voucherId"`
			} `json:"vouchers,omitempty"`
		} `json:"items"`

		// OtaOrderId Channel's order number
		OtaOrderId string `json:"otaOrderId"`

		// SequenceId GGT batch number (`yyyyMMdd` + GUID without separators)
		SequenceId string `json:"sequenceId"`

		// SupplierOrderId GGT order number
		SupplierOrderId string `json:"supplierOrderId"`
	} `json:"body"`

	// Header Standard GGT request header
	Header struct {
		// AccountId Channel's account, provided by GGT
		AccountId string `json:"accountId"`

		// RequestTime Request timestamp in `yyyy-MM-dd HH:mm:ss` format
		RequestTime time.Time `json:"requestTime"`

		// ServiceName Interface Name, one of CreatePreOrder, PayPreOrder, PayPreOrderConfirm, CancelPreOrder, CancelOrder, CancelOrderConfirm, OrderConsumedNotice, QueryOrder, QueryProduct, SupplierBalanceQuery based on APIs. For ResourcePriceSync API - DatePriceModify, For ResourceInventorySync API - DateInventoryModify
		ServiceName string `json:"serviceName"`

		// Sign Signature string for payload integrity, see signature algorithm
		Sign string `json:"sign"`

		// Version API version - 1.0
		Version string `json:"version"`
	} `json:"header"`
}

// ResourcePriceSyncJSONBody defines parameters for ResourcePriceSync.
type ResourcePriceSyncJSONBody struct {
	// Body Request body (AES-encrypted)
	Body struct {
		// DateType Date type:
		// - `DATE_REQUIRED`: Dated products (date required, up to 90 days).
		// - `DATE_NOT_REQUIRED`: Open-date products (no date).
		DateType ResourcePriceSyncJSONBodyBodyDateType `json:"dateType"`

		// OtaOptionId Channel's resource ID (not required if `supplierOptionId` is provided)
		OtaOptionId *int `json:"otaOptionId,omitempty"`

		// Prices Price nodes (retail update `salePrice`; non-retail update `costPrice`)
		Prices []struct {
			// CostPrice Settlement price
			CostPrice float32 `json:"costPrice"`

			// Date Date (`yyyy-MM-dd`).
			// Only required when `dateType=DATE_REQUIRED`.
			// Up to 90 days per request.
			Date *openapi_types.Date `json:"date,omitempty"`

			// SalePrice Offer price
			SalePrice float32 `json:"salePrice"`
		} `json:"prices"`

		// SequenceId GGT batch number (`yyyyMMdd` + GUID)
		SequenceId string `json:"sequenceId"`

		// SupplierOptionId Supplier’s PLU (not required if `otaOptionId` is provided)
		SupplierOptionId *string `json:"supplierOptionId,omitempty"`
	} `json:"body"`

	// Header Standard GGT request header
	Header struct {
		// AccountId Channel's account, provided by GGT
		AccountId string `json:"accountId"`

		// RequestTime Request timestamp in `yyyy-MM-dd HH:mm:ss` format
		RequestTime time.Time `json:"requestTime"`

		// ServiceName Interface Name, one of CreatePreOrder, PayPreOrder, PayPreOrderConfirm, CancelPreOrder, CancelOrder, CancelOrderConfirm, OrderConsumedNotice, QueryOrder, QueryProduct, SupplierBalanceQuery based on APIs. For ResourcePriceSync API - DatePriceModify, For ResourceInventorySync API - DateInventoryModify
		ServiceName string `json:"serviceName"`

		// Sign Signature string for payload integrity, see signature algorithm
		Sign string `json:"sign"`

		// Version API version - 1.0
		Version string `json:"version"`
	} `json:"header"`
}

// ResourcePriceSyncJSONBodyBodyDateType defines parameters for ResourcePriceSync.
type ResourcePriceSyncJSONBodyBodyDateType string

// ResourceInventorySyncJSONBody defines parameters for ResourceInventorySync.
type ResourceInventorySyncJSONBody struct {
	// Body request body (AES-encrypted)
	Body struct {
		// DateType Date type:
		// - `DATE_REQUIRED`: Dated products (date required, up to 90 days)
		// - `DATE_NOT_REQUIRED`: Open-date products (no date)
		DateType ResourceInventorySyncJSONBodyBodyDateType `json:"dateType"`

		// Inventories Array of inventory nodes (saleable quantity per date)
		Inventories []struct {
			// Date Date (`yyyy-MM-dd`).
			// Only when `dateType=DATE_REQUIRED`.
			// Up to 90 days per request.
			Date *openapi_types.Date `json:"date,omitempty"`

			// Quantity Saleable inventory
			Quantity int `json:"quantity"`
		} `json:"inventories"`

		// OtaOptionId Channel resource ID (omit if `supplierOptionId` provided)
		OtaOptionId *int `json:"otaOptionId,omitempty"`

		// SequenceId GGT batch number (`yyyyMMdd`+GUID)
		SequenceId string `json:"sequenceId"`

		// SupplierOptionId Supplier’s PLU (omit if `otaOptionId` provided)
		SupplierOptionId *string `json:"supplierOptionId,omitempty"`
	} `json:"body"`

	// Header Standard GGT request header
	Header struct {
		// AccountId Channel's account, provided by GGT
		AccountId string `json:"accountId"`

		// RequestTime Request timestamp in `yyyy-MM-dd HH:mm:ss` format
		RequestTime time.Time `json:"requestTime"`

		// ServiceName Interface Name, one of CreatePreOrder, PayPreOrder, PayPreOrderConfirm, CancelPreOrder, CancelOrder, CancelOrderConfirm, OrderConsumedNotice, QueryOrder, QueryProduct, SupplierBalanceQuery based on APIs. For ResourcePriceSync API - DatePriceModify, For ResourceInventorySync API - DateInventoryModify
		ServiceName string `json:"serviceName"`

		// Sign Signature string for payload integrity, see signature algorithm
		Sign string `json:"sign"`

		// Version API version - 1.0
		Version string `json:"version"`
	} `json:"header"`
}

// ResourceInventorySyncJSONBodyBodyDateType defines parameters for ResourceInventorySync.
type ResourceInventorySyncJSONBodyBodyDateType string

// UploadImageJSONBody defines parameters for UploadImage.
type UploadImageJSONBody struct {
	// ImageUrl The image URL to upload
	ImageUrl string `json:"imageUrl"`
}

// SyncProductJSONBody defines parameters for SyncProduct.
type SyncProductJSONBody struct {
	AdditionalInfo string `json:"additionalInfo"`

	// BookingSettings Booking rules of the product.
	BookingSettings struct {
		// BookingType Booking type.
		BookingType struct {
			// DateLimit Details of date limit.
			DateLimit struct {
				// CustomizedDateRange Customized time duration (only for Customized).
				CustomizedDateRange *struct {
					// FromDate Start date (yyyy-MM-dd).
					FromDate openapi_types.Date `json:"fromDate"`

					// ToDate End date (yyyy-MM-dd).
					ToDate openapi_types.Date `json:"toDate"`
				} `json:"customizedDateRange,omitempty"`

				// DateLimitType Limit type: "Single_Date" (only valid on the visit date),
				// "Multi_Date" (valid within a duration),
				// "Customized" (custom date range),
				// "Unlimited" (no limit).
				DateLimitType SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType `json:"dateLimitType"`

				// MultiDateDuration Number of days the ticket is valid (only for Multi_Date).
				MultiDateDuration *int `json:"multiDateDuration,omitempty"`
			} `json:"dateLimit"`

			// DateType Indicates whether customer must specify a visit date when booking.
			// One of "DATE_REQUIRED" (date mandatory) or "DATE_NOT_REQUIRED".
			DateType SyncProductJSONBodyBookingSettingsBookingTypeDateType `json:"dateType"`
		} `json:"bookingType"`
	} `json:"bookingSettings"`

	// CancellationPolicy Cancellation policy.
	CancellationPolicy struct {
		// ConfirmationTime How many hours to wait for the cancellation result.
		// Options: 8, 16, or 24.
		ConfirmationTime SyncProductJSONBodyCancellationPolicyConfirmationTime `json:"confirmationTime"`

		// RateList Only for By_Visit_Date: list of cancellation fees by day.
		RateList *[]struct {
			// DayBeforeVisitDate Number of days before the visit date.
			DayBeforeVisitDate int `json:"dayBeforeVisitDate"`

			// Time Time on that day (HH:mm).
			Time string `json:"time"`

			// Unit Rate unit (only "PERCENTAGE" supported).
			Unit SyncProductJSONBodyCancellationPolicyRateListUnit `json:"unit"`

			// Value Rate value (percentage).
			Value int `json:"value"`
		} `json:"rateList,omitempty"`

		// Type Cancellation type of the product:
		// "Non_Cancellable", "Free_Cancel" (any time), or "By_Visit_Date".
		Type SyncProductJSONBodyCancellationPolicyType `json:"type"`
	} `json:"cancellationPolicy"`
	Category []struct {
		// Code GGT category code
		Code SyncProductJSONBodyCategoryCode `json:"code"`
	} `json:"category"`

	// ContractId Contract ID between supplier and channel
	ContractId int `json:"contractId"`

	// Description Rich-text product description.
	Description string `json:"description"`

	// Duration Duration of the product or itinerary segment
	Duration struct {
		// Unit Unit of time
		Unit SyncProductJSONBodyDurationUnit `json:"unit"`

		// Value Amount of time
		Value int `json:"value"`
	} `json:"duration"`

	// Exclusions Free-text fees excluded.
	Exclusions []string `json:"exclusions"`
	Gallery    []struct {
		// ChannelImageId channel needs to return image ID
		ChannelImageId string `json:"channelImageId"`
	} `json:"gallery"`

	// GuestInformation Guest information needed when booking an order.
	GuestInformation struct {
		// Code Guest booking questions.
		// Possible values are "GUEST_NAME", "COUNTRY", "BIRTH_DATE", "PassportNo", etc.
		Code []SyncProductJSONBodyGuestInformationCode `json:"code"`

		// Type How much guest information is needed in one order.
		Type SyncProductJSONBodyGuestInformationType `json:"type"`
	} `json:"guestInformation"`
	Highlight []string `json:"highlight"`
	HowToUse  []string `json:"howToUse"`

	// Inclusions Free-text fees included.
	Inclusions []string `json:"inclusions"`
	Itinerary  []struct {
		// Description Additional trip-start description
		Description *string `json:"description,omitempty"`

		// Duration Duration of the product or itinerary segment
		Duration *struct {
			// Unit Unit of time
			Unit SyncProductJSONBodyItineraryDurationUnit `json:"unit"`

			// Value Amount of time
			Value int `json:"value"`
		} `json:"duration,omitempty"`

		// End End point(s) information
		End *[]struct {
			// EndTime End time in 24-hour format (HH:mm)
			EndTime string `json:"endTime"`

			// EndType How the trip ends:
			// - End_on_the_Spot: Trip ends at the spot
			// - End_After_Return: Trip ends after return to start
			// - Drop_Off_Everyone: Supplier drops off all guests
			EndType SyncProductJSONBodyItineraryEndEndType `json:"endType"`

			// Location One or more end‐point locations
			Location []SyncProductJSONBody_Itinerary_End_Location_Item `json:"location"`
		} `json:"end,omitempty"`

		// Start Start point(s) information
		Start *[]struct {
			// Location One or more start‐point locations
			Location []SyncProductJSONBody_Itinerary_Start_Location_Item `json:"location"`

			// StartTime Start time in 24-hour format (HH:mm)
			StartTime string `json:"startTime"`

			// StartType How the trip starts:
			// - Meet_at_Start_Point: Guests meet at a designated spot
			// - Pickup_Everyone: Supplier picks up all guests
			StartType SyncProductJSONBodyItineraryStartStartType `json:"startType"`
		} `json:"start,omitempty"`
	} `json:"itinerary"`

	// MetaData Extended information in JSON or free text
	MetaData *string `json:"metaData,omitempty"`

	// Option Option objects when product requires option or time slot selection.
	Option *[]struct {
		// OptionCode Option code. GGT supports "Option" or "Time_Slot".
		OptionCode SyncProductJSONBodyOptionOptionCode `json:"optionCode"`
	} `json:"option,omitempty"`

	// PaymentConfirmationTime Minutes allowed for customer to complete payment after order creation.
	PaymentConfirmationTime SyncProductJSONBodyPaymentConfirmationTime `json:"paymentConfirmationTime"`
	Poi                     []SyncProductJSONBody_Poi_Item             `json:"poi"`

	// PrimaryLanguage Language code of the primary product content.
	PrimaryLanguage SyncProductJSONBodyPrimaryLanguage `json:"primaryLanguage"`

	// RawDescription Unstructured free-text itinerary description. Required when `itinerary` is not provided
	// for Day-tour category products.
	RawDescription string `json:"rawDescription"`

	// RedemptionInfo Ticket redemption information
	RedemptionInfo struct {
		// Description Additional redemption instructions
		Description *string `json:"description,omitempty"`

		// RedemptionLocation One or more redemption locations
		RedemptionLocation []SyncProductJSONBody_RedemptionInfo_RedemptionLocation_Item `json:"redemptionLocation"`

		// RedemptionType Redemption type
		RedemptionType SyncProductJSONBodyRedemptionInfoRedemptionType `json:"redemptionType"`
	} `json:"redemptionInfo"`

	// Reference Optional supplier identifier.
	Reference       string `json:"reference"`
	ServiceLanguage []struct {
		// LanguageCode ISO language code
		LanguageCode SyncProductJSONBodyServiceLanguageLanguageCode `json:"languageCode"`
	} `json:"serviceLanguage"`

	// Status Product status (active=valid, inactive=not valid).
	Status SyncProductJSONBodyStatus `json:"status"`

	// SupplierProductId The supplier product id.
	SupplierProductId string `json:"supplierProductId"`
	Tags              []struct {
		// Id Product tag id
		Id string `json:"id"`

		// TagName Product tag name
		TagName string `json:"tagName"`
	} `json:"tags"`

	// TicketInfo Ticket delivery method information
	TicketInfo struct {
		// DeliveryMethods Ticket delivery method
		DeliveryMethods SyncProductJSONBodyTicketInfoDeliveryMethods `json:"deliveryMethods"`
	} `json:"ticketInfo"`

	// TicketType Ticket type information per product unit.
	TicketType []struct {
		// Code Ticket type code. All codes except "Customized" are predefined.
		Code SyncProductJSONBodyTicketTypeCode `json:"code"`

		// CustomCode Custom ticket code; required if code is "Customized".
		CustomCode *string `json:"customCode,omitempty"`

		// CustomName Custom ticket name; required if code is "Customized".
		CustomName *string `json:"customName,omitempty"`

		// Description Additional description of the ticket type.
		Description *string `json:"description,omitempty"`

		// Restrictions Restrictions of ticket type.
		Restrictions *struct {
			// MaxAge Maximum age.
			MaxAge *int `json:"maxAge,omitempty"`

			// MinAge Minimum age (cannot be 0).
			MinAge *int `json:"minAge,omitempty"`
		} `json:"restrictions,omitempty"`
	} `json:"ticketType"`

	// Title Supplier product name.
	Title string `json:"title"`
}

// SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType defines parameters for SyncProduct.
type SyncProductJSONBodyBookingSettingsBookingTypeDateLimitDateLimitType string

// SyncProductJSONBodyBookingSettingsBookingTypeDateType defines parameters for SyncProduct.
type SyncProductJSONBodyBookingSettingsBookingTypeDateType string

// SyncProductJSONBodyCancellationPolicyConfirmationTime defines parameters for SyncProduct.
type SyncProductJSONBodyCancellationPolicyConfirmationTime int

// SyncProductJSONBodyCancellationPolicyRateListUnit defines parameters for SyncProduct.
type SyncProductJSONBodyCancellationPolicyRateListUnit string

// SyncProductJSONBodyCancellationPolicyType defines parameters for SyncProduct.
type SyncProductJSONBodyCancellationPolicyType string

// SyncProductJSONBodyCategoryCode defines parameters for SyncProduct.
type SyncProductJSONBodyCategoryCode string

// SyncProductJSONBodyDurationUnit defines parameters for SyncProduct.
type SyncProductJSONBodyDurationUnit string

// SyncProductJSONBodyGuestInformationCode defines parameters for SyncProduct.
type SyncProductJSONBodyGuestInformationCode string

// SyncProductJSONBodyGuestInformationType defines parameters for SyncProduct.
type SyncProductJSONBodyGuestInformationType string

// SyncProductJSONBodyItineraryDurationUnit defines parameters for SyncProduct.
type SyncProductJSONBodyItineraryDurationUnit string

// SyncProductJSONBodyItineraryEndEndType defines parameters for SyncProduct.
type SyncProductJSONBodyItineraryEndEndType string

// SyncProductJSONBodyItineraryEndLocation0 defines parameters for SyncProduct.
type SyncProductJSONBodyItineraryEndLocation0 struct {
	SupplierPOI struct {
		MappingElements struct {
			// AddressDetail Address detail
			AddressDetail string `json:"addressDetail"`

			// Latitude Latitude
			Latitude float32 `json:"latitude"`

			// Longitude Longitude
			Longitude float32 `json:"longitude"`

			// Name Location name
			Name string `json:"name"`
		} `json:"mappingElements"`

		// SupplierId Supplier POI ID
		SupplierId string `json:"supplierId"`
	} `json:"supplierPOI"`
}

// SyncProductJSONBodyItineraryEndLocation1 defines parameters for SyncProduct.
type SyncProductJSONBodyItineraryEndLocation1 struct {
	// GooglePlaceId Google Place ID
	GooglePlaceId string `json:"googlePlaceId"`
}

// SyncProductJSONBody_Itinerary_End_Location_Item defines parameters for SyncProduct.
type SyncProductJSONBody_Itinerary_End_Location_Item struct {
	union json.RawMessage
}

// SyncProductJSONBodyItineraryStartLocation0 defines parameters for SyncProduct.
type SyncProductJSONBodyItineraryStartLocation0 struct {
	SupplierPOI struct {
		MappingElements struct {
			// AddressDetail Address detail
			AddressDetail string `json:"addressDetail"`

			// Latitude Latitude
			Latitude float32 `json:"latitude"`

			// Longitude Longitude
			Longitude float32 `json:"longitude"`

			// Name Location name
			Name string `json:"name"`
		} `json:"mappingElements"`

		// SupplierId Supplier POI ID
		SupplierId string `json:"supplierId"`
	} `json:"supplierPOI"`
}

// SyncProductJSONBodyItineraryStartLocation1 defines parameters for SyncProduct.
type SyncProductJSONBodyItineraryStartLocation1 struct {
	// GooglePlaceId Google Place ID
	GooglePlaceId string `json:"googlePlaceId"`
}

// SyncProductJSONBody_Itinerary_Start_Location_Item defines parameters for SyncProduct.
type SyncProductJSONBody_Itinerary_Start_Location_Item struct {
	union json.RawMessage
}

// SyncProductJSONBodyItineraryStartStartType defines parameters for SyncProduct.
type SyncProductJSONBodyItineraryStartStartType string

// SyncProductJSONBodyOptionOptionCode defines parameters for SyncProduct.
type SyncProductJSONBodyOptionOptionCode string

// SyncProductJSONBodyPaymentConfirmationTime defines parameters for SyncProduct.
type SyncProductJSONBodyPaymentConfirmationTime int

// SyncProductJSONBodyPoi0 defines parameters for SyncProduct.
type SyncProductJSONBodyPoi0 struct {
	SupplierPOI struct {
		MappingElements struct {
			// AddressDetail Address detail
			AddressDetail string `json:"addressDetail"`

			// Latitude Latitude
			Latitude float32 `json:"latitude"`

			// Longitude Longitude
			Longitude float32 `json:"longitude"`

			// Name Location name
			Name string `json:"name"`
		} `json:"mappingElements"`

		// SupplierId Supplier POI ID
		SupplierId string `json:"supplierId"`
	} `json:"supplierPOI"`
}

// SyncProductJSONBodyPoi1 defines parameters for SyncProduct.
type SyncProductJSONBodyPoi1 struct {
	// GooglePlaceId Google Place ID
	GooglePlaceId string `json:"googlePlaceId"`
}

// SyncProductJSONBody_Poi_Item defines parameters for SyncProduct.
type SyncProductJSONBody_Poi_Item struct {
	union json.RawMessage
}

// SyncProductJSONBodyPrimaryLanguage defines parameters for SyncProduct.
type SyncProductJSONBodyPrimaryLanguage string

// SyncProductJSONBodyRedemptionInfoRedemptionLocation0 defines parameters for SyncProduct.
type SyncProductJSONBodyRedemptionInfoRedemptionLocation0 struct {
	SupplierLocation struct {
		MappingElements struct {
			AddressDetail string  `json:"addressDetail"`
			Latitude      float32 `json:"latitude"`
			Longitude     float32 `json:"longitude"`
			Name          string  `json:"name"`
		} `json:"mappingElements"`
		SupplierId string `json:"supplierId"`
	} `json:"supplierLocation"`
}

// SyncProductJSONBodyRedemptionInfoRedemptionLocation1 defines parameters for SyncProduct.
type SyncProductJSONBodyRedemptionInfoRedemptionLocation1 struct {
	GooglePlaceId string `json:"googlePlaceId"`
}

// SyncProductJSONBody_RedemptionInfo_RedemptionLocation_Item defines parameters for SyncProduct.
type SyncProductJSONBody_RedemptionInfo_RedemptionLocation_Item struct {
	union json.RawMessage
}

// SyncProductJSONBodyRedemptionInfoRedemptionType defines parameters for SyncProduct.
type SyncProductJSONBodyRedemptionInfoRedemptionType string

// SyncProductJSONBodyServiceLanguageLanguageCode defines parameters for SyncProduct.
type SyncProductJSONBodyServiceLanguageLanguageCode string

// SyncProductJSONBodyStatus defines parameters for SyncProduct.
type SyncProductJSONBodyStatus string

// SyncProductJSONBodyTicketInfoDeliveryMethods defines parameters for SyncProduct.
type SyncProductJSONBodyTicketInfoDeliveryMethods string

// SyncProductJSONBodyTicketTypeCode defines parameters for SyncProduct.
type SyncProductJSONBodyTicketTypeCode string

// SyncPackageJSONBody defines parameters for SyncPackage.
type SyncPackageJSONBody struct {
	// OptionList Option list of this package.
	OptionList []struct {
		// BookingCutOffTime When ordering must cut off for this option
		BookingCutOffTime struct {
			// DayBeforeVisitDate Number of days before visit date
			DayBeforeVisitDate string `json:"dayBeforeVisitDate"`

			// Time Time of day (HH:mm) on that cutoff day
			Time string `json:"time"`
		} `json:"bookingCutOffTime"`

		// BookingQuestions Questions the customer must answer when selecting this option. Each is answered once per order.
		BookingQuestions *[]struct {
			// AllowedAnswers One allowed answer for a single-selection question
			AllowedAnswers *struct {
				// Code Supplier’s answer code
				Code string `json:"code"`

				// Name Human-readable answer
				Name string `json:"name"`
			} `json:"allowedAnswers,omitempty"`

			// AnswerType Type of answer expected
			AnswerType SyncPackageJSONBodyOptionListBookingQuestionsAnswerType `json:"answerType"`

			// Code Supplier’s question code
			Code string `json:"code"`

			// Description Hint or help text for this question
			Description *string `json:"description,omitempty"`

			// Name Human-readable question
			Name string `json:"name"`
		} `json:"bookingQuestions,omitempty"`

		// Option List of selectable values for this option
		Option []struct {
			// OptionCode One of: `Option`, `Time_Slot`.
			// This code must be configured first in your sync-product endpoint.
			OptionCode string `json:"optionCode"`

			// ValueCode Option value code
			ValueCode string `json:"valueCode"`

			// ValueName Human-readable option name.
			// Must match the primary language.
			ValueName string `json:"valueName"`
		} `json:"option"`

		// OptionDescription Free-text description of this option
		OptionDescription *string `json:"optionDescription,omitempty"`

		// OptionStatus Option status:
		// - `active` = valid
		// - `inactive` = not valid
		OptionStatus SyncPackageJSONBodyOptionListOptionStatus `json:"optionStatus"`

		// Unit Definition of each “unit” (PLU) available under this option. Used for pricing & ordering.
		Unit []struct {
			// PLU Supplier’s minimum-unit code
			PLU string `json:"PLU"`

			// Currency ISO currency codes for this unit’s pricing
			Currency struct {
				// NetPriceCurrency Currency of the net (supplier) price (ISO 4217)
				NetPriceCurrency string `json:"netPriceCurrency"`

				// RetailPriceCurrency Currency of the retail (customer) price (ISO 4217)
				RetailPriceCurrency string `json:"retailPriceCurrency"`
			} `json:"currency"`

			// CustomCode Only for Customized ticketTypeCode
			CustomCode *string `json:"customCode,omitempty"`

			// NetPriceCurrency Currency of the net price (ISO)
			NetPriceCurrency string `json:"netPriceCurrency"`

			// Reference Optional supplier reference for this unit
			Reference *string `json:"reference,omitempty"`

			// Restrictions Booking/unit restrictions for one product unit
			Restrictions struct {
				// CompanionRequired Whether this unit can be booked alone (Not_Required) or must accompany another.
				CompanionRequired SyncPackageJSONBodyOptionListUnitRestrictionsCompanionRequired `json:"companionRequired"`

				// MaxUnits Maximum booking quantity per order
				MaxUnits string `json:"maxUnits"`

				// MinUnits Minimum booking quantity per order
				MinUnits string `json:"minUnits"`

				// UnitPax Number of people this unit covers (e.g. 1 for single, 4 for family)
				UnitPax string `json:"unitPax"`
			} `json:"restrictions"`

			// RetailPriceCurrency Currency of the retail price (ISO)
			RetailPriceCurrency string `json:"retailPriceCurrency"`

			// TicketTypeCode Must match a TicketType.code defined elsewhere
			TicketTypeCode SyncPackageJSONBodyOptionListUnitTicketTypeCode `json:"ticketTypeCode"`
		} `json:"unit"`
	} `json:"optionList"`

	// SupplierProductId The supplier product id.
	SupplierProductId string `json:"supplierProductId"`
}

// SyncPackageJSONBodyOptionListBookingQuestionsAnswerType defines parameters for SyncPackage.
type SyncPackageJSONBodyOptionListBookingQuestionsAnswerType string

// SyncPackageJSONBodyOptionListOptionStatus defines parameters for SyncPackage.
type SyncPackageJSONBodyOptionListOptionStatus string

// SyncPackageJSONBodyOptionListUnitRestrictionsCompanionRequired defines parameters for SyncPackage.
type SyncPackageJSONBodyOptionListUnitRestrictionsCompanionRequired string

// SyncPackageJSONBodyOptionListUnitTicketTypeCode defines parameters for SyncPackage.
type SyncPackageJSONBodyOptionListUnitTicketTypeCode string

// ExternalHandlerJSONBody defines parameters for ExternalHandler.
type ExternalHandlerJSONBody struct {
	union json.RawMessage
}

// PayPreOrderConfirmJSONRequestBody defines body for PayPreOrderConfirm for application/json ContentType.
type PayPreOrderConfirmJSONRequestBody PayPreOrderConfirmJSONBody

// CancelOrderConfirmJSONRequestBody defines body for CancelOrderConfirm for application/json ContentType.
type CancelOrderConfirmJSONRequestBody CancelOrderConfirmJSONBody

// OrderConsumedNotificationJSONRequestBody defines body for OrderConsumedNotification for application/json ContentType.
type OrderConsumedNotificationJSONRequestBody OrderConsumedNotificationJSONBody

// ResourcePriceSyncJSONRequestBody defines body for ResourcePriceSync for application/json ContentType.
type ResourcePriceSyncJSONRequestBody ResourcePriceSyncJSONBody

// ResourceInventorySyncJSONRequestBody defines body for ResourceInventorySync for application/json ContentType.
type ResourceInventorySyncJSONRequestBody ResourceInventorySyncJSONBody

// UploadImageJSONRequestBody defines body for UploadImage for application/json ContentType.
type UploadImageJSONRequestBody UploadImageJSONBody

// SyncProductJSONRequestBody defines body for SyncProduct for application/json ContentType.
type SyncProductJSONRequestBody SyncProductJSONBody

// SyncPackageJSONRequestBody defines body for SyncPackage for application/json ContentType.
type SyncPackageJSONRequestBody SyncPackageJSONBody

// ExternalHandlerJSONRequestBody defines body for ExternalHandler for application/json ContentType.
type ExternalHandlerJSONRequestBody ExternalHandlerJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Pay Pre-order Confirmation
	// (POST /channelEndpoint1)
	PayPreOrderConfirm(c *gin.Context)
	// Order cancellation confirmation
	// (POST /channelEndpoint2)
	CancelOrderConfirm(c *gin.Context)
	// Order consumed notification
	// (POST /channelEndpoint3)
	OrderConsumedNotification(c *gin.Context)
	// Resource price sync
	// (POST /channelEndpoint4)
	ResourcePriceSync(c *gin.Context)
	// Resource inventory sync
	// (POST /channelEndpoint5)
	ResourceInventorySync(c *gin.Context)
	// Upload image
	// (POST /channelEndpoint6)
	UploadImage(c *gin.Context)
	// Sync product
	// (POST /channelEndpoint7)
	SyncProduct(c *gin.Context)
	// Sync package
	// (POST /channelEndpoint8)
	SyncPackage(c *gin.Context)
	// All Order APIs
	// (POST /external)
	ExternalHandler(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PayPreOrderConfirm operation middleware
func (siw *ServerInterfaceWrapper) PayPreOrderConfirm(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PayPreOrderConfirm(c)
}

// CancelOrderConfirm operation middleware
func (siw *ServerInterfaceWrapper) CancelOrderConfirm(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelOrderConfirm(c)
}

// OrderConsumedNotification operation middleware
func (siw *ServerInterfaceWrapper) OrderConsumedNotification(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OrderConsumedNotification(c)
}

// ResourcePriceSync operation middleware
func (siw *ServerInterfaceWrapper) ResourcePriceSync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResourcePriceSync(c)
}

// ResourceInventorySync operation middleware
func (siw *ServerInterfaceWrapper) ResourceInventorySync(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResourceInventorySync(c)
}

// UploadImage operation middleware
func (siw *ServerInterfaceWrapper) UploadImage(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadImage(c)
}

// SyncProduct operation middleware
func (siw *ServerInterfaceWrapper) SyncProduct(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SyncProduct(c)
}

// SyncPackage operation middleware
func (siw *ServerInterfaceWrapper) SyncPackage(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SyncPackage(c)
}

// ExternalHandler operation middleware
func (siw *ServerInterfaceWrapper) ExternalHandler(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExternalHandler(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/channelEndpoint1", wrapper.PayPreOrderConfirm)
	router.POST(options.BaseURL+"/channelEndpoint2", wrapper.CancelOrderConfirm)
	router.POST(options.BaseURL+"/channelEndpoint3", wrapper.OrderConsumedNotification)
	router.POST(options.BaseURL+"/channelEndpoint4", wrapper.ResourcePriceSync)
	router.POST(options.BaseURL+"/channelEndpoint5", wrapper.ResourceInventorySync)
	router.POST(options.BaseURL+"/channelEndpoint6", wrapper.UploadImage)
	router.POST(options.BaseURL+"/channelEndpoint7", wrapper.SyncProduct)
	router.POST(options.BaseURL+"/channelEndpoint8", wrapper.SyncPackage)
	router.POST(options.BaseURL+"/external", wrapper.ExternalHandler)
}
