// Package get_your_guide provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package get_your_guide

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Defines values for AddonAddonType.
const (
	AddonAddonTypeDONATION  AddonAddonType = "DONATION"
	AddonAddonTypeDRINKS    AddonAddonType = "DRINKS"
	AddonAddonTypeFOOD      AddonAddonType = "FOOD"
	AddonAddonTypeOTHERS    AddonAddonType = "OTHERS"
	AddonAddonTypeSAFETY    AddonAddonType = "SAFETY"
	AddonAddonTypeTRANSPORT AddonAddonType = "TRANSPORT"
)

// Defines values for AddonItemAddonType.
const (
	AddonItemAddonTypeDONATION  AddonItemAddonType = "DONATION"
	AddonItemAddonTypeDRINKS    AddonItemAddonType = "DRINKS"
	AddonItemAddonTypeFOOD      AddonItemAddonType = "FOOD"
	AddonItemAddonTypeOTHERS    AddonItemAddonType = "OTHERS"
	AddonItemAddonTypeSAFETY    AddonItemAddonType = "SAFETY"
	AddonItemAddonTypeTRANSPORT AddonItemAddonType = "TRANSPORT"
)

// Defines values for AddonsErrorResponseErrorCode.
const (
	AddonsErrorResponseErrorCodeAUTHORIZATIONFAILURE  AddonsErrorResponseErrorCode = "AUTHORIZATION_FAILURE"
	AddonsErrorResponseErrorCodeINTERNALSYSTEMFAILURE AddonsErrorResponseErrorCode = "INTERNAL_SYSTEM_FAILURE"
	AddonsErrorResponseErrorCodeINVALIDPRODUCT        AddonsErrorResponseErrorCode = "INVALID_PRODUCT"
)

// Defines values for AvailabilityPricesByCategoryRetailPricesCategory.
const (
	AvailabilityPricesByCategoryRetailPricesCategoryADULT            AvailabilityPricesByCategoryRetailPricesCategory = "ADULT"
	AvailabilityPricesByCategoryRetailPricesCategoryCHILD            AvailabilityPricesByCategoryRetailPricesCategory = "CHILD"
	AvailabilityPricesByCategoryRetailPricesCategoryEUCITIZEN        AvailabilityPricesByCategoryRetailPricesCategory = "EU_CITIZEN"
	AvailabilityPricesByCategoryRetailPricesCategoryEUCITIZENSTUDENT AvailabilityPricesByCategoryRetailPricesCategory = "EU_CITIZEN_STUDENT"
	AvailabilityPricesByCategoryRetailPricesCategoryGROUP            AvailabilityPricesByCategoryRetailPricesCategory = "GROUP"
	AvailabilityPricesByCategoryRetailPricesCategoryINFANT           AvailabilityPricesByCategoryRetailPricesCategory = "INFANT"
	AvailabilityPricesByCategoryRetailPricesCategoryMILITARY         AvailabilityPricesByCategoryRetailPricesCategory = "MILITARY"
	AvailabilityPricesByCategoryRetailPricesCategorySENIOR           AvailabilityPricesByCategoryRetailPricesCategory = "SENIOR"
	AvailabilityPricesByCategoryRetailPricesCategorySTUDENT          AvailabilityPricesByCategoryRetailPricesCategory = "STUDENT"
	AvailabilityPricesByCategoryRetailPricesCategoryYOUTH            AvailabilityPricesByCategoryRetailPricesCategory = "YOUTH"
)

// Defines values for AvailabilityTieredPricesByCategoryRetailPricesCategory.
const (
	AvailabilityTieredPricesByCategoryRetailPricesCategoryADULT            AvailabilityTieredPricesByCategoryRetailPricesCategory = "ADULT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryCHILD            AvailabilityTieredPricesByCategoryRetailPricesCategory = "CHILD"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryEUCITIZEN        AvailabilityTieredPricesByCategoryRetailPricesCategory = "EU_CITIZEN"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryEUCITIZENSTUDENT AvailabilityTieredPricesByCategoryRetailPricesCategory = "EU_CITIZEN_STUDENT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryGROUP            AvailabilityTieredPricesByCategoryRetailPricesCategory = "GROUP"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryINFANT           AvailabilityTieredPricesByCategoryRetailPricesCategory = "INFANT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryMILITARY         AvailabilityTieredPricesByCategoryRetailPricesCategory = "MILITARY"
	AvailabilityTieredPricesByCategoryRetailPricesCategorySENIOR           AvailabilityTieredPricesByCategoryRetailPricesCategory = "SENIOR"
	AvailabilityTieredPricesByCategoryRetailPricesCategorySTUDENT          AvailabilityTieredPricesByCategoryRetailPricesCategory = "STUDENT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryYOUTH            AvailabilityTieredPricesByCategoryRetailPricesCategory = "YOUTH"
)

// Defines values for Category.
const (
	CategoryADULT            Category = "ADULT"
	CategoryCHILD            Category = "CHILD"
	CategoryEUCITIZEN        Category = "EU_CITIZEN"
	CategoryEUCITIZENSTUDENT Category = "EU_CITIZEN_STUDENT"
	CategoryGROUP            Category = "GROUP"
	CategoryINFANT           Category = "INFANT"
	CategoryMILITARY         Category = "MILITARY"
	CategorySENIOR           Category = "SENIOR"
	CategorySTUDENT          Category = "STUDENT"
	CategoryYOUTH            Category = "YOUTH"
)

// Defines values for CategoryCollective.
const (
	CategoryCollectiveADULT            CategoryCollective = "ADULT"
	CategoryCollectiveCHILD            CategoryCollective = "CHILD"
	CategoryCollectiveCOLLECTIVE       CategoryCollective = "COLLECTIVE"
	CategoryCollectiveEUCITIZEN        CategoryCollective = "EU_CITIZEN"
	CategoryCollectiveEUCITIZENSTUDENT CategoryCollective = "EU_CITIZEN_STUDENT"
	CategoryCollectiveGROUP            CategoryCollective = "GROUP"
	CategoryCollectiveINFANT           CategoryCollective = "INFANT"
	CategoryCollectiveMILITARY         CategoryCollective = "MILITARY"
	CategoryCollectiveSENIOR           CategoryCollective = "SENIOR"
	CategoryCollectiveSTUDENT          CategoryCollective = "STUDENT"
	CategoryCollectiveYOUTH            CategoryCollective = "YOUTH"
)

// Defines values for CategoryConfigurationBookingCategory.
const (
	FREENOTICKET       CategoryConfigurationBookingCategory = "FREE_NO_TICKET"
	FREETICKETREQUIRED CategoryConfigurationBookingCategory = "FREE_TICKET_REQUIRED"
	NOTPERMITTED       CategoryConfigurationBookingCategory = "NOT_PERMITTED"
	STANDARD           CategoryConfigurationBookingCategory = "STANDARD"
)

// Defines values for ErrorGroupSizeConstraintErrorCode.
const (
	ErrorGroupSizeConstraintErrorCodeINVALIDPARTICIPANTSCONFIGURATION ErrorGroupSizeConstraintErrorCode = "INVALID_PARTICIPANTS_CONFIGURATION"
)

// Defines values for ErrorParticipantSizeConstraintErrorCode.
const (
	ErrorParticipantSizeConstraintErrorCodeINVALIDPARTICIPANTSCONFIGURATION ErrorParticipantSizeConstraintErrorCode = "INVALID_PARTICIPANTS_CONFIGURATION"
)

// Defines values for ErrorResponseAvailabilityErrorCode.
const (
	ErrorResponseAvailabilityErrorCodeAUTHORIZATIONFAILURE  ErrorResponseAvailabilityErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseAvailabilityErrorCodeINTERNALSYSTEMFAILURE ErrorResponseAvailabilityErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseAvailabilityErrorCodeINVALIDPRODUCT        ErrorResponseAvailabilityErrorCode = "INVALID_PRODUCT"
	ErrorResponseAvailabilityErrorCodeVALIDATIONFAILURE     ErrorResponseAvailabilityErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseBookingErrorCode.
const (
	ErrorResponseBookingErrorCodeAUTHORIZATIONFAILURE       ErrorResponseBookingErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseBookingErrorCodeINTERNALSYSTEMFAILURE      ErrorResponseBookingErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseBookingErrorCodeINVALIDADDONSCONFIGURATION ErrorResponseBookingErrorCode = "INVALID_ADDONS_CONFIGURATION"
	ErrorResponseBookingErrorCodeINVALIDRESERVATION         ErrorResponseBookingErrorCode = "INVALID_RESERVATION"
	ErrorResponseBookingErrorCodeINVALIDTICKETCATEGORY      ErrorResponseBookingErrorCode = "INVALID_TICKET_CATEGORY"
	ErrorResponseBookingErrorCodeNOAVAILABILITY             ErrorResponseBookingErrorCode = "NO_AVAILABILITY"
	ErrorResponseBookingErrorCodeVALIDATIONFAILURE          ErrorResponseBookingErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseBookingCancellationErrorCode.
const (
	ErrorResponseBookingCancellationErrorCodeAUTHORIZATIONFAILURE   ErrorResponseBookingCancellationErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseBookingCancellationErrorCodeBOOKINGALREADYCANCELED ErrorResponseBookingCancellationErrorCode = "BOOKING_ALREADY_CANCELED"
	ErrorResponseBookingCancellationErrorCodeBOOKINGINPAST          ErrorResponseBookingCancellationErrorCode = "BOOKING_IN_PAST"
	ErrorResponseBookingCancellationErrorCodeBOOKINGREDEEMED        ErrorResponseBookingCancellationErrorCode = "BOOKING_REDEEMED"
	ErrorResponseBookingCancellationErrorCodeINTERNALSYSTEMFAILURE  ErrorResponseBookingCancellationErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseBookingCancellationErrorCodeINVALIDBOOKING         ErrorResponseBookingCancellationErrorCode = "INVALID_BOOKING"
	ErrorResponseBookingCancellationErrorCodeVALIDATIONFAILURE      ErrorResponseBookingCancellationErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseReservationErrorCode.
const (
	ErrorResponseReservationErrorCodeAUTHORIZATIONFAILURE  ErrorResponseReservationErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseReservationErrorCodeINTERNALSYSTEMFAILURE ErrorResponseReservationErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseReservationErrorCodeINVALIDPRODUCT        ErrorResponseReservationErrorCode = "INVALID_PRODUCT"
	ErrorResponseReservationErrorCodeINVALIDTICKETCATEGORY ErrorResponseReservationErrorCode = "INVALID_TICKET_CATEGORY"
	ErrorResponseReservationErrorCodeNOAVAILABILITY        ErrorResponseReservationErrorCode = "NO_AVAILABILITY"
	ErrorResponseReservationErrorCodeVALIDATIONFAILURE     ErrorResponseReservationErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseReservationCancellationErrorCode.
const (
	ErrorResponseReservationCancellationErrorCodeAUTHORIZATIONFAILURE  ErrorResponseReservationCancellationErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseReservationCancellationErrorCodeINTERNALSYSTEMFAILURE ErrorResponseReservationCancellationErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseReservationCancellationErrorCodeINVALIDRESERVATION    ErrorResponseReservationCancellationErrorCode = "INVALID_RESERVATION"
	ErrorResponseReservationCancellationErrorCodeVALIDATIONFAILURE     ErrorResponseReservationCancellationErrorCode = "VALIDATION_FAILURE"
)

// Defines values for NotificationDataNotificationType.
const (
	PRODUCTDEACTIVATION NotificationDataNotificationType = "PRODUCT_DEACTIVATION"
)

// Defines values for PricePriceType.
const (
	RETAILPRICE PricePriceType = "RETAIL_PRICE"
)

// Defines values for ProductDetailsErrorResponseErrorCode.
const (
	ProductDetailsErrorResponseErrorCodeAUTHORIZATIONFAILURE  ProductDetailsErrorResponseErrorCode = "AUTHORIZATION_FAILURE"
	ProductDetailsErrorResponseErrorCodeINTERNALSYSTEMFAILURE ProductDetailsErrorResponseErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ProductDetailsErrorResponseErrorCodeINVALIDPRODUCT        ProductDetailsErrorResponseErrorCode = "INVALID_PRODUCT"
)

// Defines values for ProductsListErrorResponseErrorCode.
const (
	ProductsListErrorResponseErrorCodeAUTHORIZATIONFAILURE  ProductsListErrorResponseErrorCode = "AUTHORIZATION_FAILURE"
	ProductsListErrorResponseErrorCodeINTERNALSYSTEMFAILURE ProductsListErrorResponseErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ProductsListErrorResponseErrorCodeINVALIDSUPPLIER       ProductsListErrorResponseErrorCode = "INVALID_SUPPLIER"
)

// Defines values for TicketCodeType.
const (
	AZTEC          TicketCodeType = "AZTEC"
	BARCODECODE128 TicketCodeType = "BARCODE_CODE128"
	BARCODECODE39  TicketCodeType = "BARCODE_CODE39"
	DATAMATRIX     TicketCodeType = "DATA_MATRIX"
	EAN13          TicketCodeType = "EAN_13"
	ITF            TicketCodeType = "ITF"
	QRCODE         TicketCodeType = "QR_CODE"
	TEXT           TicketCodeType = "TEXT"
)

// Defines values for VacanciesByCategoryCategory.
const (
	ADULT            VacanciesByCategoryCategory = "ADULT"
	CHILD            VacanciesByCategoryCategory = "CHILD"
	EUCITIZEN        VacanciesByCategoryCategory = "EU_CITIZEN"
	EUCITIZENSTUDENT VacanciesByCategoryCategory = "EU_CITIZEN_STUDENT"
	INFANT           VacanciesByCategoryCategory = "INFANT"
	MILITARY         VacanciesByCategoryCategory = "MILITARY"
	SENIOR           VacanciesByCategoryCategory = "SENIOR"
	STUDENT          VacanciesByCategoryCategory = "STUDENT"
	YOUTH            VacanciesByCategoryCategory = "YOUTH"
)

// Addon defines model for Addon.
type Addon struct {
	// AddonDescription The description of the addon in your system. Max 50 characters. This field is optional but required and must be unique when multiple addons with the same addonType are present in the response.
	AddonDescription *string `json:"addonDescription,omitempty"`

	// AddonType The Addon Type which is provided during booking.
	AddonType AddonAddonType `json:"addonType"`

	// Currency Code of the currency (ISO 4217), using alphabetic code and three characters in length. Must be a supported currency.
	Currency string `json:"currency"`

	// RetailPrice Integer representation of the smallest unit of the currency. F.e. 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. F.e. 5000 JPY should be price 5000.
	RetailPrice int `json:"retailPrice"`
}

// AddonAddonType The Addon Type which is provided during booking.
type AddonAddonType string

// AddonItem defines model for AddonItem.
type AddonItem struct {
	// AddonDescription The description of the addon in your system. Max 50 characters. This field is optional but required and must be unique when multiple addons with the same addonType are present in the response.
	AddonDescription *string `json:"addonDescription,omitempty"`

	// AddonType The Addon Type which is provided during booking.
	AddonType *AddonItemAddonType `json:"addonType,omitempty"`

	// Count The number of Addon being booked for the specified Addon.
	Count *int `json:"count,omitempty"`

	// RetailPrice Integer representation of the smallest unit of the currency. F.e. 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. F.e. 5000 JPY should be price 5000.
	RetailPrice *int `json:"retailPrice,omitempty"`
}

// AddonItemAddonType The Addon Type which is provided during booking.
type AddonItemAddonType string

// AddonsErrorResponse defines model for AddonsErrorResponse.
type AddonsErrorResponse struct {
	ErrorCode    AddonsErrorResponseErrorCode `json:"errorCode"`
	ErrorMessage *string                      `json:"errorMessage,omitempty"`
}

// AddonsErrorResponseErrorCode defines model for AddonsErrorResponse.ErrorCode.
type AddonsErrorResponseErrorCode string

// AddonsResponse defines model for AddonsResponse.
type AddonsResponse struct {
	// Data A successful data response containing addons list information
	Data GetAddonsSuccessResponse `json:"data"`
}

// Availability defines model for Availability.
type Availability struct {
	// Currency Code of the currency (ISO 4217), using alphabetic code and three characters in length. Must be a supported currency. Example: "EUR"
	Currency *string `json:"currency,omitempty"`

	// CutoffSeconds Cut-off time expressed in seconds for the availability of a specific product (the time until which a product can be booked). This field can be 0
	CutoffSeconds *int `json:"cutoffSeconds,omitempty"`

	// DateTime The date/time of the activity (ISO 8601). Content of the time part depends on the type (see time point vs time period).
	DateTime time.Time `json:"dateTime"`

	// OpeningTimes A list of opening times (from/to pairs) for time period product only. Should be in the format HH:MM
	OpeningTimes *[]struct {
		// FromTime Example: "09:00"
		FromTime *string `json:"fromTime,omitempty"`

		// ToTime Example: "12:00"
		ToTime *string `json:"toTime,omitempty"`
	} `json:"openingTimes,omitempty"`

	// PricesByCategory Object representing the prices of the product
	PricesByCategory *struct {
		// RetailPrices List of retail prices per categories
		RetailPrices []struct {
			// Category The category for which the retail price is being provided.
			Category AvailabilityPricesByCategoryRetailPricesCategory `json:"category"`

			// Price Integer representation of the smallest unit of the currency. Example: 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. Example: 5000 JPY should be price 5000
			Price int `json:"price"`
		} `json:"retailPrices"`
	} `json:"pricesByCategory,omitempty"`

	// ProductId The ID of the requested product in the supplier’s system that this availability refers to.
	ProductId string `json:"productId"`

	// TieredPricesByCategory Object representing the tiered prices of the product
	TieredPricesByCategory *struct {
		// RetailPrices List of tiered prices per categories
		RetailPrices *[]struct {
			// Category The category for which the retail price is being provided.
			Category *AvailabilityTieredPricesByCategoryRetailPricesCategory `json:"category,omitempty"`

			// Tiers List of prices with tiers
			Tiers *[]struct {
				// LowerBound The minimum number of participants for this price tier. Inclusive.
				LowerBound *int `json:"lowerBound,omitempty"`

				// Price Integer representation of the smallest unit of the currency. Example: 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. Example: 5000 JPY should be price 5000
				Price *int `json:"price,omitempty"`

				// UpperBound The maximum number of participants for this price tier. Inclusive.
				UpperBound *int `json:"upperBound"`
			} `json:"tiers,omitempty"`
		} `json:"retailPrices,omitempty"`
	} `json:"tieredPricesByCategory,omitempty"`

	// Vacancies For Individual ticket categories, this is the total number of vacancies across all categories for the requested product at the time slot specified in the dateTime field. If the product has “unlimited” availability please use a large value here. E.g. 5000. For GROUP products, this is the total number of available groups, not the total number of individual vacancies.
	//
	// **Note** - The "vacancies" field has an internal GetYourGuide cap of "5000". If received vacancies exceed 5000 for any DateTimeslot, GetYourGuide will still cap the value to 5000
	Vacancies *int `json:"vacancies,omitempty"`

	// VacanciesByCategory For Individual ticket categories, this is the number of vacancies available for each ticket category for the requested product at the time slot specified in the dateTime field. For GROUP products, this isn't supported.
	VacanciesByCategory *[]VacanciesByCategory `json:"vacanciesByCategory,omitempty"`
	union               json.RawMessage
}

// AvailabilityPricesByCategoryRetailPricesCategory The category for which the retail price is being provided.
type AvailabilityPricesByCategoryRetailPricesCategory string

// AvailabilityTieredPricesByCategoryRetailPricesCategory The category for which the retail price is being provided.
type AvailabilityTieredPricesByCategoryRetailPricesCategory string

// Availability0 defines model for .
type Availability0 = interface{}

// Availability1 defines model for .
type Availability1 = interface{}

// AvailabilityResponse defines model for AvailabilityResponse.
type AvailabilityResponse struct {
	Data struct {
		Availabilities []Availability `json:"availabilities"`
	} `json:"data"`
}

// BookingCancellationRequest defines model for BookingCancellationRequest.
type BookingCancellationRequest struct {
	Data struct {
		// BookingReference An alphanumeric identifier for the booking in the supplier’s system. Maximum length of 25 characters. Example: GYG123JKE453-sf3321C
		BookingReference string `json:"bookingReference"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`.
		ProductId string `json:"productId"`
	} `json:"data"`
}

// BookingItem defines model for BookingItem.
type BookingItem struct {
	// Category The category for which the number of persons is being provided.
	Category Category `json:"category"`

	// Count The number of persons being reserved for the specified category. When bookingItems[].category is GROUP this will always be 1. If we are reserving multiple groups we will add multiple bookingItems.
	Count int `json:"count"`

	// GroupSize Indicates the amount of pax per group, only provided in the context of a bookingItem of category type GROUP. The number of persons being reserved for the specified category. When bookingItems[].category is GROUP it must indicate the number of persons in that group.
	GroupSize *int `json:"groupSize,omitempty"`

	// RetailPrice The basic retail price in the given currency that GetYourGuide charged the customer for one participant of this category during the booking process. This will be sent for all options, regardless of whether Price Over API is enabled. The received retailPrice must never be the reason to fail the booking request. If you observe a wrong price being sent, do not reject the booking and reach out to the Connectivity Support team.
	RetailPrice int `json:"retailPrice"`
}

// BookingRequest defines model for BookingRequest.
type BookingRequest struct {
	Data *struct {
		// AddonItems A list of objects containing information about the addons of this booking.
		AddonItems *[]AddonItem `json:"addonItems,omitempty"`

		// BookingItems A list specifying the number of persons per category in this reservation. The data will be the same as in the corresponding field of the reservation call.
		BookingItems []BookingItem `json:"bookingItems"`

		// Comment Additional information provided by the traveler, e.g., [pick up](https://supplier-support.getyourguide.com/en/support/solutions/articles/15000030542-setting-meeting-point-and-pickup), dietary restrictions, weight, passport, etc. Please note this parameter could contain several thousand characters of unstructured data (free text).<br>
		// Note: this field will always be part of the request. If configured for this product on GetYourGuide it will be filled with the information required, otherwise it will be sent as a string containin only <code>"\n"</code>
		Comment string `json:"comment"`

		// Currency The currency of the retail prices in the request.
		Currency string `json:"currency"`

		// DateTime The date/time of the activity to be reserved (ISO 8601). The date/time of the activity (ISO 8601). Content of the time part is depending on the type (see time point vs time period above).
		DateTime time.Time `json:"dateTime"`

		// GygActivityReference The reference of this activity in GetYourGuide’s system.
		GygActivityReference *string `json:"gygActivityReference,omitempty"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// Language ISO 639-1 code of the language in which the product shall be booked.
		Language *string `json:"language,omitempty"`

		// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`.
		ProductId string `json:"productId"`

		// ReservationReference The identifier for the reservation in the supplier’s system as returned by the reserve call.
		ReservationReference string `json:"reservationReference"`

		// TravelerHotel The traveler’s hotel. This is provided to facilitate pickup where applicable.
		TravelerHotel *string `json:"travelerHotel,omitempty"`

		// Travelers A list of objects containing information about the travelers of this booking. The number of elements does not necessarily match the total indicated by the bookingItems parameter. As default, only the lead traveler is sent, unless set up differently on the Supplier Admin.
		Travelers []Traveler `json:"travelers"`
	} `json:"data,omitempty"`
}

// BookingResponse defines model for BookingResponse.
type BookingResponse struct {
	Data struct {
		// BookingReference An alphanumeric identifier for the booking in the supplier’s system. Maximum length of 25 characters. Example: GYG123JKE453-sf3321C
		BookingReference string   `json:"bookingReference"`
		Tickets          []Ticket `json:"tickets"`
	} `json:"data"`
}

// Category The category for which the number of persons is being provided.
type Category string

// CategoryCollective The category of the ticket. The returned categories must match the type and the count of requested items. Alternatively GetYourGuide accepts 1 (and only 1) `COLLECTIVE` ticket.
type CategoryCollective string

// CategoryConfiguration defines model for CategoryConfiguration.
type CategoryConfiguration struct {
	// AgeFrom The minimum age for a person to fall into this category. If no minimum applies, set to null
	AgeFrom *int `json:"ageFrom"`

	// AgeTo The maximum age for a person to fall into this category. If no maximum applies, set to null
	AgeTo *int `json:"ageTo"`

	// BookingCategory The booking type for this category. The default is STANDARD
	BookingCategory *CategoryConfigurationBookingCategory `json:"bookingCategory"`

	// Category The category associated with this configuration
	Category *string `json:"category,omitempty"`

	// GroupSizeMax The maximum amount of participants in one group
	GroupSizeMax *int `json:"groupSizeMax"`

	// GroupSizeMin The minimum amount of participants in one group
	GroupSizeMin *int `json:"groupSizeMin"`

	// MaxTicketAmount The maximum amount of tickets for this category allowed in one booking
	MaxTicketAmount *int `json:"maxTicketAmount"`

	// MinTicketAmount The minimum amount of tickets for this category allowed in one booking.
	MinTicketAmount *int     `json:"minTicketAmount"`
	Price           *[]Price `json:"price"`
}

// CategoryConfigurationBookingCategory The booking type for this category. The default is STANDARD
type CategoryConfigurationBookingCategory string

// DestinationLocation defines model for DestinationLocation.
type DestinationLocation struct {
	// City The city in which the product is located. Must be in UN/LOCODE NameWoDiacritics format.
	City string `json:"city"`

	// Country The country in which the product is located. Must be in ISO 3166-1 alpha-3 format.
	Country string `json:"country"`
}

// EmptySuccessResponse defines model for EmptySuccessResponse.
type EmptySuccessResponse struct {
	Data *map[string]interface{} `json:"data,omitempty"`
}

// ErrorGroupSizeConstraint defines model for ErrorGroupSizeConstraint.
type ErrorGroupSizeConstraint struct {
	ErrorCode                 ErrorGroupSizeConstraintErrorCode `json:"errorCode"`
	ErrorMessage              *string                           `json:"errorMessage,omitempty"`
	GroupConfiguration        GroupConfiguration                `json:"groupConfiguration"`
	ParticipantsConfiguration ParticipantsConfiguration         `json:"participantsConfiguration"`
}

// ErrorGroupSizeConstraintErrorCode defines model for ErrorGroupSizeConstraint.ErrorCode.
type ErrorGroupSizeConstraintErrorCode string

// ErrorParticipantSizeConstraint defines model for ErrorParticipantSizeConstraint.
type ErrorParticipantSizeConstraint struct {
	ErrorCode                 ErrorParticipantSizeConstraintErrorCode `json:"errorCode"`
	ErrorMessage              *string                                 `json:"errorMessage,omitempty"`
	ParticipantsConfiguration ParticipantsConfiguration               `json:"participantsConfiguration"`
}

// ErrorParticipantSizeConstraintErrorCode defines model for ErrorParticipantSizeConstraint.ErrorCode.
type ErrorParticipantSizeConstraintErrorCode string

// ErrorResponseAvailability defines model for ErrorResponseAvailability.
type ErrorResponseAvailability struct {
	ErrorCode    ErrorResponseAvailabilityErrorCode `json:"errorCode"`
	ErrorMessage *string                            `json:"errorMessage,omitempty"`
}

// ErrorResponseAvailabilityErrorCode defines model for ErrorResponseAvailability.ErrorCode.
type ErrorResponseAvailabilityErrorCode string

// ErrorResponseBooking defines model for ErrorResponseBooking.
type ErrorResponseBooking struct {
	ErrorCode    ErrorResponseBookingErrorCode `json:"errorCode"`
	ErrorMessage *string                       `json:"errorMessage,omitempty"`
}

// ErrorResponseBookingErrorCode defines model for ErrorResponseBooking.ErrorCode.
type ErrorResponseBookingErrorCode string

// ErrorResponseBookingCancellation defines model for ErrorResponseBookingCancellation.
type ErrorResponseBookingCancellation struct {
	ErrorCode    ErrorResponseBookingCancellationErrorCode `json:"errorCode"`
	ErrorMessage *string                                   `json:"errorMessage,omitempty"`
}

// ErrorResponseBookingCancellationErrorCode defines model for ErrorResponseBookingCancellation.ErrorCode.
type ErrorResponseBookingCancellationErrorCode string

// ErrorResponseReservation defines model for ErrorResponseReservation.
type ErrorResponseReservation struct {
	ErrorCode    ErrorResponseReservationErrorCode `json:"errorCode"`
	ErrorMessage *string                           `json:"errorMessage,omitempty"`
}

// ErrorResponseReservationErrorCode defines model for ErrorResponseReservation.ErrorCode.
type ErrorResponseReservationErrorCode string

// ErrorResponseReservationCancellation defines model for ErrorResponseReservationCancellation.
type ErrorResponseReservationCancellation struct {
	ErrorCode    ErrorResponseReservationCancellationErrorCode `json:"errorCode"`
	ErrorMessage *string                                       `json:"errorMessage,omitempty"`
}

// ErrorResponseReservationCancellationErrorCode defines model for ErrorResponseReservationCancellation.ErrorCode.
type ErrorResponseReservationCancellationErrorCode string

// GetAddonsSuccessResponse A successful data response containing addons list information
type GetAddonsSuccessResponse struct {
	// Addons List of all valid addons for a product. If no addons are available for the product, the list should be empty.
	Addons []Addon `json:"addons"`
}

// GetPricingCategoriesSuccessResponse defines model for GetPricingCategoriesSuccessResponse.
type GetPricingCategoriesSuccessResponse struct {
	PricingCategories *[]CategoryConfiguration `json:"pricingCategories,omitempty"`
}

// GroupConfiguration defines model for GroupConfiguration.
type GroupConfiguration struct {
	// Max The maximum number of Groups allowed per booking.
	Max int `json:"max"`
}

// Notification defines model for Notification.
type Notification struct {
	Data NotificationData `json:"data"`
}

// NotificationData defines model for NotificationData.
type NotificationData struct {
	// DateTime The date/time when the notification is sent (ISO 8601).
	DateTime time.Time `json:"dateTime"`

	// Description The description of the notification.
	Description string `json:"description"`

	// IntegrationName The name of the system that the affected product is connected to.
	IntegrationName     string                               `json:"integrationName"`
	NotificationDetails NotificationData_NotificationDetails `json:"notificationDetails"`
	NotificationType    NotificationDataNotificationType     `json:"notificationType"`

	// ProductDetails Details of the affected product.
	ProductDetails NotificationDataProductDetails `json:"productDetails"`

	// SupplierName The supplier name of the affected product.
	SupplierName string `json:"supplierName"`
}

// NotificationData_NotificationDetails defines model for NotificationData.NotificationDetails.
type NotificationData_NotificationDetails struct {
	union json.RawMessage
}

// NotificationDataNotificationType defines model for NotificationData.NotificationType.
type NotificationDataNotificationType string

// NotificationDataProductDetails Details of the affected product.
type NotificationDataProductDetails struct {
	// GygTourOptionId The unique ID of the affected product (tour option) in the GYG’s system.
	GygTourOptionId string `json:"gygTourOptionId"`

	// ProductId The ID of the affected product in the supplier’s system.
	ProductId string `json:"productId"`

	// TourOptionTitle The title of the affected product.
	TourOptionTitle *string `json:"tourOptionTitle,omitempty"`
}

// ParticipantsConfiguration defines model for ParticipantsConfiguration.
type ParticipantsConfiguration struct {
	Max *int `json:"max"`
	Min int  `json:"min"`
}

// Price An object containing price information
type Price struct {
	// Currency Code of the currency (ISO 4217), using alphabetic code and three characters in length. Must be a supported currency.
	Currency *string `json:"currency,omitempty"`

	// Price Integer representation of the smallest unit of the currency. F.e. 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. F.e. 5000 JPY should be price 5000
	Price *int `json:"price,omitempty"`

	// PriceType The type of the price
	PriceType *PricePriceType `json:"priceType,omitempty"`
}

// PricePriceType The type of the price
type PricePriceType string

// PricingCategoriesResponse defines model for PricingCategoriesResponse.
type PricingCategoriesResponse struct {
	Data GetPricingCategoriesSuccessResponse `json:"data"`
}

// ProductConfiguration defines model for ProductConfiguration.
type ProductConfiguration struct {
	ParticipantsConfiguration *ProductDetailsParticipantsConfiguration `json:"participantsConfiguration,omitempty"`
}

// ProductDeactivationDataDetails The details of the notification, which could be different from one notification type to another. The properties shown below are the details for a specific notification type `PRODUCT_DEACTIVATION`, which is the only notification type GYG sends to the endpoint at the current moment.
type ProductDeactivationDataDetails struct {
	// ActivityStartTime The start date/time of the requested product in the failed request (ISO 8601). The content of the time part depends on the type (see time point vs time period under [General Definitions](/documentation/overview#section/General-Definitions)).
	ActivityStartTime *time.Time `json:"activityStartTime,omitempty"`

	// ActivityTimeZone The local timezone of the affected product.
	ActivityTimeZone *string `json:"activityTimeZone,omitempty"`

	// DeactivationTimestamp The date/time when the product is deacitvated in GYG's system (ISO 8601).
	DeactivationTimestamp *time.Time `json:"deactivationTimestamp,omitempty"`

	// ErrorMessageReceived The error message received from your system to the failed request.
	ErrorMessageReceived *string `json:"errorMessageReceived,omitempty"`

	// ErrorType The error type received from your system in the response to the failed request.
	ErrorType *string `json:"errorType,omitempty"`

	// FailedRequestType The type of failed request that causes the pruduct deactivation.
	FailedRequestType *string `json:"failedRequestType,omitempty"`

	// GygBookingReference The booking reference of the failed request in GYG’s system.
	GygBookingReference *string `json:"gygBookingReference,omitempty"`

	// Travellers The number of participants were reserved for the specified categories in the failed reservation request. Different ticket categories, e.g., adult and child, are separated using commas.
	Travellers *string `json:"travellers,omitempty"`

	// VacanciesReceivedAfterGetAvailability The vacancies were received from your system during the get-availability check after the failed reservation request.
	VacanciesReceivedAfterGetAvailability *string `json:"vacanciesReceivedAfterGetAvailability,omitempty"`
}

// ProductDetailsErrorResponse defines model for ProductDetailsErrorResponse.
type ProductDetailsErrorResponse struct {
	ErrorCode    ProductDetailsErrorResponseErrorCode `json:"errorCode"`
	ErrorMessage *string                              `json:"errorMessage,omitempty"`
}

// ProductDetailsErrorResponseErrorCode defines model for ProductDetailsErrorResponse.ErrorCode.
type ProductDetailsErrorResponseErrorCode string

// ProductDetailsParticipantsConfiguration defines model for ProductDetailsParticipantsConfiguration.
type ProductDetailsParticipantsConfiguration struct {
	Max *int `json:"max"`
	Min *int `json:"min"`
}

// ProductDetailsResponse defines model for ProductDetailsResponse.
type ProductDetailsResponse struct {
	Data ProductDetailsResponseData `json:"data"`
}

// ProductDetailsResponseData defines model for ProductDetailsResponseData.
type ProductDetailsResponseData struct {
	Configuration       *ProductConfiguration `json:"configuration,omitempty"`
	DestinationLocation DestinationLocation   `json:"destinationLocation"`

	// ProductDescription The description of the product on the Partner platform (SRS). Must be maximum 512 characters long.
	ProductDescription *string `json:"productDescription,omitempty"`

	// ProductTitle The name/Title of the product on the Partner platform (SRS). Must be maximum 512 characters long.
	ProductTitle string `json:"productTitle"`

	// SupplierId The Supplier ID of the supplier on the Partner platform (SRS).
	SupplierId string `json:"supplierId"`
}

// ProductsListErrorResponse defines model for ProductsListErrorResponse.
type ProductsListErrorResponse struct {
	ErrorCode    ProductsListErrorResponseErrorCode `json:"errorCode"`
	ErrorMessage *string                            `json:"errorMessage,omitempty"`
}

// ProductsListErrorResponseErrorCode defines model for ProductsListErrorResponse.ErrorCode.
type ProductsListErrorResponseErrorCode string

// ReservationBookingItem defines model for ReservationBookingItem.
type ReservationBookingItem struct {
	// Category The category for which the number of persons is being provided.
	Category Category `json:"category"`

	// Count The number of persons being reserved for the specified category. When bookingItems[].category is GROUP this will always be 1. If we are reserving multiple groups we will add multiple bookingItems.
	Count int `json:"count"`

	// GroupSize Indicates the amount of pax per group, only provided in the context of a bookingItem of category type GROUP. The number of persons being reserved for the specified category. When bookingItems[].category is GROUP it must indicate the number of persons in that group.
	GroupSize *int `json:"groupSize,omitempty"`
}

// ReservationCancellationRequest defines model for ReservationCancellationRequest.
type ReservationCancellationRequest struct {
	Data struct {
		// GygActivityReference The GYG tour option id which is getting cancelled
		GygActivityReference *string `json:"gygActivityReference,omitempty"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// ReservationReference The identifier for the reservation in the supplier’s system as returned by the reserve call.
		ReservationReference string `json:"reservationReference"`
	} `json:"data"`
}

// ReservationRequest defines model for ReservationRequest.
type ReservationRequest struct {
	Data struct {
		// BookingItems A list specifying the number of persons per category in this reservation.
		BookingItems []ReservationBookingItem `json:"bookingItems"`

		// DateTime The date/time of the activity to be reserved (ISO 8601). For the time period products, the time of the activity is always set to `00:00:00` of the requested travel date (see time point vs time period under [General Definitions](/documentation/overview#section/General-Definitions)).
		DateTime time.Time `json:"dateTime"`

		// GygActivityReference The reference of this activity in GetYourGuide’s system.
		GygActivityReference *string `json:"gygActivityReference,omitempty"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`.
		ProductId string `json:"productId"`
	} `json:"data"`
}

// ReservationResponse defines model for ReservationResponse.
type ReservationResponse struct {
	Data struct {
		ReservationExpiration *time.Time `json:"reservationExpiration,omitempty"`

		// ReservationReference The identifier for the reservation in the supplier’s system as returned by the reserve call.
		ReservationReference string `json:"reservationReference"`
	} `json:"data"`
}

// SupplierProduct defines model for SupplierProduct.
type SupplierProduct struct {
	// ProductId The ID of the product A on the Partner platform (SRS).
	ProductId string `json:"productId"`

	// ProductTitle The name of the product A on the Partner platform (SRS). Must be maximum 512 characters long.
	ProductTitle string `json:"productTitle"`
}

// SupplierProductsResponse defines model for SupplierProductsResponse.
type SupplierProductsResponse struct {
	Data SupplierProductsResponseData `json:"data"`
}

// SupplierProductsResponseData defines model for SupplierProductsResponseData.
type SupplierProductsResponseData struct {
	Products []SupplierProduct `json:"products"`

	// SupplierId The Supplier ID of the supplier on the Partner platform (SRS).
	SupplierId string `json:"supplierId"`

	// SupplierName The name of the supplier on the Partner platform (SRS). Must be maximum 512 characters long.
	SupplierName *string `json:"supplierName,omitempty"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	// Category The category of the ticket. The returned categories must match the type and the count of requested items. Alternatively GetYourGuide accepts 1 (and only 1) `COLLECTIVE` ticket.
	Category CategoryCollective `json:"category"`

	// TicketCode The ticket code.<br> If the `TicketCodeType` is `BARCODE_CODE39`, `BARCODE_CODE128` or `ITF` the max lenght of the value is 80 characters.<br> If the `TicketCodeType` is `EAN_13` the lenght of the value must be 12 or 13 characters (lower & upper bound).<br> For all the other `TicketCodeType` the max lenght of the value is 512 characters.
	TicketCode string `json:"ticketCode"`

	// TicketCodeType Indicates how the ticket code shall be rendered on the customer’s voucher.
	TicketCodeType TicketCodeType `json:"ticketCodeType"`
}

// TicketCodeType Indicates how the ticket code shall be rendered on the customer’s voucher.
type TicketCodeType string

// Traveler defines model for Traveler.
type Traveler struct {
	// Email Email address of the traveler
	Email string `json:"email"`

	// FirstName First name of the traveler.
	FirstName string `json:"firstName"`

	// LastName Last name of the traveler.
	LastName string `json:"lastName"`

	// PhoneNumber Phone number of the traveler
	PhoneNumber string `json:"phoneNumber"`
}

// VacanciesByCategory defines model for VacanciesByCategory.
type VacanciesByCategory struct {
	// Category The ticket categories for which the availabilities is being provided.
	Category VacanciesByCategoryCategory `json:"category"`

	// Vacancies The number of vacancies available for the ticket Category.
	Vacancies int `json:"vacancies"`
}

// VacanciesByCategoryCategory The ticket categories for which the availabilities is being provided.
type VacanciesByCategoryCategory string

// GetGetAvailabilitiesParams defines parameters for GetGetAvailabilities.
type GetGetAvailabilitiesParams struct {
	// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`, as it is used as an escape character in URL encoding and may cause encoding/decoding failures in query parameters.
	ProductId string `form:"productId" json:"productId"`

	// FromDateTime Marks the start (inclusive) of the requested time period (ISO 8601).
	FromDateTime string `form:"fromDateTime" json:"fromDateTime"`

	// ToDateTime Marks the end (inclusive) of the requested time period (ISO 8601).
	ToDateTime string `form:"toDateTime" json:"toDateTime"`
}

// PostBookJSONRequestBody defines body for PostBook for application/json ContentType.
type PostBookJSONRequestBody = BookingRequest

// PostCancelBookingJSONRequestBody defines body for PostCancelBooking for application/json ContentType.
type PostCancelBookingJSONRequestBody = BookingCancellationRequest

// PostCancelReservationJSONRequestBody defines body for PostCancelReservation for application/json ContentType.
type PostCancelReservationJSONRequestBody = ReservationCancellationRequest

// PostNotifyJSONRequestBody defines body for PostNotify for application/json ContentType.
type PostNotifyJSONRequestBody = Notification

// PostReserveJSONRequestBody defines body for PostReserve for application/json ContentType.
type PostReserveJSONRequestBody = ReservationRequest

// AsAvailability0 returns the union data inside the Availability as a Availability0
func (t Availability) AsAvailability0() (Availability0, error) {
	var body Availability0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAvailability0 overwrites any union data inside the Availability as the provided Availability0
func (t *Availability) FromAvailability0(v Availability0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAvailability0 performs a merge with any union data inside the Availability, using the provided Availability0
func (t *Availability) MergeAvailability0(v Availability0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAvailability1 returns the union data inside the Availability as a Availability1
func (t Availability) AsAvailability1() (Availability1, error) {
	var body Availability1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAvailability1 overwrites any union data inside the Availability as the provided Availability1
func (t *Availability) FromAvailability1(v Availability1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAvailability1 performs a merge with any union data inside the Availability, using the provided Availability1
func (t *Availability) MergeAvailability1(v Availability1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Availability) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Currency != nil {
		object["currency"], err = json.Marshal(t.Currency)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'currency': %w", err)
		}
	}

	if t.CutoffSeconds != nil {
		object["cutoffSeconds"], err = json.Marshal(t.CutoffSeconds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cutoffSeconds': %w", err)
		}
	}

	object["dateTime"], err = json.Marshal(t.DateTime)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'dateTime': %w", err)
	}

	if t.OpeningTimes != nil {
		object["openingTimes"], err = json.Marshal(t.OpeningTimes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'openingTimes': %w", err)
		}
	}

	if t.PricesByCategory != nil {
		object["pricesByCategory"], err = json.Marshal(t.PricesByCategory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pricesByCategory': %w", err)
		}
	}

	object["productId"], err = json.Marshal(t.ProductId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'productId': %w", err)
	}

	if t.TieredPricesByCategory != nil {
		object["tieredPricesByCategory"], err = json.Marshal(t.TieredPricesByCategory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tieredPricesByCategory': %w", err)
		}
	}

	if t.Vacancies != nil {
		object["vacancies"], err = json.Marshal(t.Vacancies)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vacancies': %w", err)
		}
	}

	if t.VacanciesByCategory != nil {
		object["vacanciesByCategory"], err = json.Marshal(t.VacanciesByCategory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vacanciesByCategory': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *Availability) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["currency"]; found {
		err = json.Unmarshal(raw, &t.Currency)
		if err != nil {
			return fmt.Errorf("error reading 'currency': %w", err)
		}
	}

	if raw, found := object["cutoffSeconds"]; found {
		err = json.Unmarshal(raw, &t.CutoffSeconds)
		if err != nil {
			return fmt.Errorf("error reading 'cutoffSeconds': %w", err)
		}
	}

	if raw, found := object["dateTime"]; found {
		err = json.Unmarshal(raw, &t.DateTime)
		if err != nil {
			return fmt.Errorf("error reading 'dateTime': %w", err)
		}
	}

	if raw, found := object["openingTimes"]; found {
		err = json.Unmarshal(raw, &t.OpeningTimes)
		if err != nil {
			return fmt.Errorf("error reading 'openingTimes': %w", err)
		}
	}

	if raw, found := object["pricesByCategory"]; found {
		err = json.Unmarshal(raw, &t.PricesByCategory)
		if err != nil {
			return fmt.Errorf("error reading 'pricesByCategory': %w", err)
		}
	}

	if raw, found := object["productId"]; found {
		err = json.Unmarshal(raw, &t.ProductId)
		if err != nil {
			return fmt.Errorf("error reading 'productId': %w", err)
		}
	}

	if raw, found := object["tieredPricesByCategory"]; found {
		err = json.Unmarshal(raw, &t.TieredPricesByCategory)
		if err != nil {
			return fmt.Errorf("error reading 'tieredPricesByCategory': %w", err)
		}
	}

	if raw, found := object["vacancies"]; found {
		err = json.Unmarshal(raw, &t.Vacancies)
		if err != nil {
			return fmt.Errorf("error reading 'vacancies': %w", err)
		}
	}

	if raw, found := object["vacanciesByCategory"]; found {
		err = json.Unmarshal(raw, &t.VacanciesByCategory)
		if err != nil {
			return fmt.Errorf("error reading 'vacanciesByCategory': %w", err)
		}
	}

	return err
}

// AsProductDeactivationDataDetails returns the union data inside the NotificationData_NotificationDetails as a ProductDeactivationDataDetails
func (t NotificationData_NotificationDetails) AsProductDeactivationDataDetails() (ProductDeactivationDataDetails, error) {
	var body ProductDeactivationDataDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProductDeactivationDataDetails overwrites any union data inside the NotificationData_NotificationDetails as the provided ProductDeactivationDataDetails
func (t *NotificationData_NotificationDetails) FromProductDeactivationDataDetails(v ProductDeactivationDataDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProductDeactivationDataDetails performs a merge with any union data inside the NotificationData_NotificationDetails, using the provided ProductDeactivationDataDetails
func (t *NotificationData_NotificationDetails) MergeProductDeactivationDataDetails(v ProductDeactivationDataDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NotificationData_NotificationDetails) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NotificationData_NotificationDetails) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Booking
	// (POST /1/book/)
	PostBook(c *gin.Context)
	// Booking Cancellation
	// (POST /1/cancel-booking/)
	PostCancelBooking(c *gin.Context)
	// Reservation Cancellation
	// (POST /1/cancel-reservation/)
	PostCancelReservation(c *gin.Context)
	// Availability Query
	// (GET /1/get-availabilities/)
	GetGetAvailabilities(c *gin.Context, params GetGetAvailabilitiesParams)
	// Notification
	// (POST /1/notify/)
	PostNotify(c *gin.Context)
	// Product Details
	// (GET /1/products/{productId})
	GetProductDetails(c *gin.Context, productId string)
	// Fetch Addons
	// (GET /1/products/{productId}/addons/)
	FetchAddons(c *gin.Context, productId string)
	// Pricing Categories
	// (GET /1/products/{productId}/pricing-categories/)
	GetPricingCategories(c *gin.Context, productId string)
	// Reservation
	// (POST /1/reserve/)
	PostReserve(c *gin.Context)
	// Products List
	// (GET /1/suppliers/{supplierId}/products/)
	GetSupplierProducts(c *gin.Context, supplierId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostBook operation middleware
func (siw *ServerInterfaceWrapper) PostBook(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostBook(c)
}

// PostCancelBooking operation middleware
func (siw *ServerInterfaceWrapper) PostCancelBooking(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCancelBooking(c)
}

// PostCancelReservation operation middleware
func (siw *ServerInterfaceWrapper) PostCancelReservation(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCancelReservation(c)
}

// GetGetAvailabilities operation middleware
func (siw *ServerInterfaceWrapper) GetGetAvailabilities(c *gin.Context) {

	var err error

	c.Set(BasicAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGetAvailabilitiesParams

	// ------------- Required query parameter "productId" -------------

	if paramValue := c.Query("productId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument productId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "productId", c.Request.URL.Query(), &params.ProductId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "fromDateTime" -------------

	if paramValue := c.Query("fromDateTime"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument fromDateTime is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "fromDateTime", c.Request.URL.Query(), &params.FromDateTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fromDateTime: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "toDateTime" -------------

	if paramValue := c.Query("toDateTime"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument toDateTime is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "toDateTime", c.Request.URL.Query(), &params.ToDateTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter toDateTime: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGetAvailabilities(c, params)
}

// PostNotify operation middleware
func (siw *ServerInterfaceWrapper) PostNotify(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostNotify(c)
}

// GetProductDetails operation middleware
func (siw *ServerInterfaceWrapper) GetProductDetails(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductDetails(c, productId)
}

// FetchAddons operation middleware
func (siw *ServerInterfaceWrapper) FetchAddons(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FetchAddons(c, productId)
}

// GetPricingCategories operation middleware
func (siw *ServerInterfaceWrapper) GetPricingCategories(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPricingCategories(c, productId)
}

// PostReserve operation middleware
func (siw *ServerInterfaceWrapper) PostReserve(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostReserve(c)
}

// GetSupplierProducts operation middleware
func (siw *ServerInterfaceWrapper) GetSupplierProducts(c *gin.Context) {

	var err error

	// ------------- Path parameter "supplierId" -------------
	var supplierId string

	err = runtime.BindStyledParameterWithOptions("simple", "supplierId", c.Param("supplierId"), &supplierId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSupplierProducts(c, supplierId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/1/book/", wrapper.PostBook)
	router.POST(options.BaseURL+"/1/cancel-booking/", wrapper.PostCancelBooking)
	router.POST(options.BaseURL+"/1/cancel-reservation/", wrapper.PostCancelReservation)
	router.GET(options.BaseURL+"/1/get-availabilities/", wrapper.GetGetAvailabilities)
	router.POST(options.BaseURL+"/1/notify/", wrapper.PostNotify)
	router.GET(options.BaseURL+"/1/products/:productId", wrapper.GetProductDetails)
	router.GET(options.BaseURL+"/1/products/:productId/addons/", wrapper.FetchAddons)
	router.GET(options.BaseURL+"/1/products/:productId/pricing-categories/", wrapper.GetPricingCategories)
	router.POST(options.BaseURL+"/1/reserve/", wrapper.PostReserve)
	router.GET(options.BaseURL+"/1/suppliers/:supplierId/products/", wrapper.GetSupplierProducts)
}
