// Package get_your_guide provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package get_your_guide

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Defines values for AddonAddonType.
const (
	AddonAddonTypeDONATION  AddonAddonType = "DONATION"
	AddonAddonTypeDRINKS    AddonAddonType = "DRINKS"
	AddonAddonTypeFOOD      AddonAddonType = "FOOD"
	AddonAddonTypeOTHERS    AddonAddonType = "OTHERS"
	AddonAddonTypeSAFETY    AddonAddonType = "SAFETY"
	AddonAddonTypeTRANSPORT AddonAddonType = "TRANSPORT"
)

// Defines values for AddonItemAddonType.
const (
	AddonItemAddonTypeDONATION  AddonItemAddonType = "DONATION"
	AddonItemAddonTypeDRINKS    AddonItemAddonType = "DRINKS"
	AddonItemAddonTypeFOOD      AddonItemAddonType = "FOOD"
	AddonItemAddonTypeOTHERS    AddonItemAddonType = "OTHERS"
	AddonItemAddonTypeSAFETY    AddonItemAddonType = "SAFETY"
	AddonItemAddonTypeTRANSPORT AddonItemAddonType = "TRANSPORT"
)

// Defines values for AddonsErrorResponseErrorCode.
const (
	AddonsErrorResponseErrorCodeAUTHORIZATIONFAILURE  AddonsErrorResponseErrorCode = "AUTHORIZATION_FAILURE"
	AddonsErrorResponseErrorCodeINTERNALSYSTEMFAILURE AddonsErrorResponseErrorCode = "INTERNAL_SYSTEM_FAILURE"
	AddonsErrorResponseErrorCodeINVALIDPRODUCT        AddonsErrorResponseErrorCode = "INVALID_PRODUCT"
)

// Defines values for AvailabilityPricesByCategoryRetailPricesCategory.
const (
	AvailabilityPricesByCategoryRetailPricesCategoryADULT            AvailabilityPricesByCategoryRetailPricesCategory = "ADULT"
	AvailabilityPricesByCategoryRetailPricesCategoryCHILD            AvailabilityPricesByCategoryRetailPricesCategory = "CHILD"
	AvailabilityPricesByCategoryRetailPricesCategoryEUCITIZEN        AvailabilityPricesByCategoryRetailPricesCategory = "EU_CITIZEN"
	AvailabilityPricesByCategoryRetailPricesCategoryEUCITIZENSTUDENT AvailabilityPricesByCategoryRetailPricesCategory = "EU_CITIZEN_STUDENT"
	AvailabilityPricesByCategoryRetailPricesCategoryGROUP            AvailabilityPricesByCategoryRetailPricesCategory = "GROUP"
	AvailabilityPricesByCategoryRetailPricesCategoryINFANT           AvailabilityPricesByCategoryRetailPricesCategory = "INFANT"
	AvailabilityPricesByCategoryRetailPricesCategoryMILITARY         AvailabilityPricesByCategoryRetailPricesCategory = "MILITARY"
	AvailabilityPricesByCategoryRetailPricesCategorySENIOR           AvailabilityPricesByCategoryRetailPricesCategory = "SENIOR"
	AvailabilityPricesByCategoryRetailPricesCategorySTUDENT          AvailabilityPricesByCategoryRetailPricesCategory = "STUDENT"
	AvailabilityPricesByCategoryRetailPricesCategoryYOUTH            AvailabilityPricesByCategoryRetailPricesCategory = "YOUTH"
)

// Defines values for AvailabilityTieredPricesByCategoryRetailPricesCategory.
const (
	AvailabilityTieredPricesByCategoryRetailPricesCategoryADULT            AvailabilityTieredPricesByCategoryRetailPricesCategory = "ADULT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryCHILD            AvailabilityTieredPricesByCategoryRetailPricesCategory = "CHILD"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryEUCITIZEN        AvailabilityTieredPricesByCategoryRetailPricesCategory = "EU_CITIZEN"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryEUCITIZENSTUDENT AvailabilityTieredPricesByCategoryRetailPricesCategory = "EU_CITIZEN_STUDENT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryGROUP            AvailabilityTieredPricesByCategoryRetailPricesCategory = "GROUP"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryINFANT           AvailabilityTieredPricesByCategoryRetailPricesCategory = "INFANT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryMILITARY         AvailabilityTieredPricesByCategoryRetailPricesCategory = "MILITARY"
	AvailabilityTieredPricesByCategoryRetailPricesCategorySENIOR           AvailabilityTieredPricesByCategoryRetailPricesCategory = "SENIOR"
	AvailabilityTieredPricesByCategoryRetailPricesCategorySTUDENT          AvailabilityTieredPricesByCategoryRetailPricesCategory = "STUDENT"
	AvailabilityTieredPricesByCategoryRetailPricesCategoryYOUTH            AvailabilityTieredPricesByCategoryRetailPricesCategory = "YOUTH"
)

// Defines values for Category.
const (
	CategoryADULT            Category = "ADULT"
	CategoryCHILD            Category = "CHILD"
	CategoryEUCITIZEN        Category = "EU_CITIZEN"
	CategoryEUCITIZENSTUDENT Category = "EU_CITIZEN_STUDENT"
	CategoryGROUP            Category = "GROUP"
	CategoryINFANT           Category = "INFANT"
	CategoryMILITARY         Category = "MILITARY"
	CategorySENIOR           Category = "SENIOR"
	CategorySTUDENT          Category = "STUDENT"
	CategoryYOUTH            Category = "YOUTH"
)

// Defines values for CategoryCollective.
const (
	CategoryCollectiveADULT            CategoryCollective = "ADULT"
	CategoryCollectiveCHILD            CategoryCollective = "CHILD"
	CategoryCollectiveCOLLECTIVE       CategoryCollective = "COLLECTIVE"
	CategoryCollectiveEUCITIZEN        CategoryCollective = "EU_CITIZEN"
	CategoryCollectiveEUCITIZENSTUDENT CategoryCollective = "EU_CITIZEN_STUDENT"
	CategoryCollectiveGROUP            CategoryCollective = "GROUP"
	CategoryCollectiveINFANT           CategoryCollective = "INFANT"
	CategoryCollectiveMILITARY         CategoryCollective = "MILITARY"
	CategoryCollectiveSENIOR           CategoryCollective = "SENIOR"
	CategoryCollectiveSTUDENT          CategoryCollective = "STUDENT"
	CategoryCollectiveYOUTH            CategoryCollective = "YOUTH"
)

// Defines values for CategoryConfigurationBookingCategory.
const (
	FREENOTICKET       CategoryConfigurationBookingCategory = "FREE_NO_TICKET"
	FREETICKETREQUIRED CategoryConfigurationBookingCategory = "FREE_TICKET_REQUIRED"
	NOTPERMITTED       CategoryConfigurationBookingCategory = "NOT_PERMITTED"
	STANDARD           CategoryConfigurationBookingCategory = "STANDARD"
)

// Defines values for ErrorGroupSizeConstraintErrorCode.
const (
	ErrorGroupSizeConstraintErrorCodeINVALIDPARTICIPANTSCONFIGURATION ErrorGroupSizeConstraintErrorCode = "INVALID_PARTICIPANTS_CONFIGURATION"
)

// Defines values for ErrorParticipantSizeConstraintErrorCode.
const (
	ErrorParticipantSizeConstraintErrorCodeINVALIDPARTICIPANTSCONFIGURATION ErrorParticipantSizeConstraintErrorCode = "INVALID_PARTICIPANTS_CONFIGURATION"
)

// Defines values for ErrorResponseAvailabilityErrorCode.
const (
	ErrorResponseAvailabilityErrorCodeAUTHORIZATIONFAILURE  ErrorResponseAvailabilityErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseAvailabilityErrorCodeINTERNALSYSTEMFAILURE ErrorResponseAvailabilityErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseAvailabilityErrorCodeINVALIDPRODUCT        ErrorResponseAvailabilityErrorCode = "INVALID_PRODUCT"
	ErrorResponseAvailabilityErrorCodeVALIDATIONFAILURE     ErrorResponseAvailabilityErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseBookingErrorCode.
const (
	ErrorResponseBookingErrorCodeAUTHORIZATIONFAILURE       ErrorResponseBookingErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseBookingErrorCodeINTERNALSYSTEMFAILURE      ErrorResponseBookingErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseBookingErrorCodeINVALIDADDONSCONFIGURATION ErrorResponseBookingErrorCode = "INVALID_ADDONS_CONFIGURATION"
	ErrorResponseBookingErrorCodeINVALIDRESERVATION         ErrorResponseBookingErrorCode = "INVALID_RESERVATION"
	ErrorResponseBookingErrorCodeINVALIDTICKETCATEGORY      ErrorResponseBookingErrorCode = "INVALID_TICKET_CATEGORY"
	ErrorResponseBookingErrorCodeNOAVAILABILITY             ErrorResponseBookingErrorCode = "NO_AVAILABILITY"
	ErrorResponseBookingErrorCodeVALIDATIONFAILURE          ErrorResponseBookingErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseBookingCancellationErrorCode.
const (
	ErrorResponseBookingCancellationErrorCodeAUTHORIZATIONFAILURE   ErrorResponseBookingCancellationErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseBookingCancellationErrorCodeBOOKINGALREADYCANCELED ErrorResponseBookingCancellationErrorCode = "BOOKING_ALREADY_CANCELED"
	ErrorResponseBookingCancellationErrorCodeBOOKINGINPAST          ErrorResponseBookingCancellationErrorCode = "BOOKING_IN_PAST"
	ErrorResponseBookingCancellationErrorCodeBOOKINGREDEEMED        ErrorResponseBookingCancellationErrorCode = "BOOKING_REDEEMED"
	ErrorResponseBookingCancellationErrorCodeINTERNALSYSTEMFAILURE  ErrorResponseBookingCancellationErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseBookingCancellationErrorCodeINVALIDBOOKING         ErrorResponseBookingCancellationErrorCode = "INVALID_BOOKING"
	ErrorResponseBookingCancellationErrorCodeVALIDATIONFAILURE      ErrorResponseBookingCancellationErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseReservationErrorCode.
const (
	ErrorResponseReservationErrorCodeAUTHORIZATIONFAILURE  ErrorResponseReservationErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseReservationErrorCodeINTERNALSYSTEMFAILURE ErrorResponseReservationErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseReservationErrorCodeINVALIDPRODUCT        ErrorResponseReservationErrorCode = "INVALID_PRODUCT"
	ErrorResponseReservationErrorCodeINVALIDTICKETCATEGORY ErrorResponseReservationErrorCode = "INVALID_TICKET_CATEGORY"
	ErrorResponseReservationErrorCodeNOAVAILABILITY        ErrorResponseReservationErrorCode = "NO_AVAILABILITY"
	ErrorResponseReservationErrorCodeVALIDATIONFAILURE     ErrorResponseReservationErrorCode = "VALIDATION_FAILURE"
)

// Defines values for ErrorResponseReservationCancellationErrorCode.
const (
	ErrorResponseReservationCancellationErrorCodeAUTHORIZATIONFAILURE  ErrorResponseReservationCancellationErrorCode = "AUTHORIZATION_FAILURE"
	ErrorResponseReservationCancellationErrorCodeINTERNALSYSTEMFAILURE ErrorResponseReservationCancellationErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ErrorResponseReservationCancellationErrorCodeINVALIDRESERVATION    ErrorResponseReservationCancellationErrorCode = "INVALID_RESERVATION"
	ErrorResponseReservationCancellationErrorCodeVALIDATIONFAILURE     ErrorResponseReservationCancellationErrorCode = "VALIDATION_FAILURE"
)

// Defines values for NotificationDataNotificationType.
const (
	PRODUCTDEACTIVATION NotificationDataNotificationType = "PRODUCT_DEACTIVATION"
)

// Defines values for PricePriceType.
const (
	RETAILPRICE PricePriceType = "RETAIL_PRICE"
)

// Defines values for ProductDetailsErrorResponseErrorCode.
const (
	ProductDetailsErrorResponseErrorCodeAUTHORIZATIONFAILURE  ProductDetailsErrorResponseErrorCode = "AUTHORIZATION_FAILURE"
	ProductDetailsErrorResponseErrorCodeINTERNALSYSTEMFAILURE ProductDetailsErrorResponseErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ProductDetailsErrorResponseErrorCodeINVALIDPRODUCT        ProductDetailsErrorResponseErrorCode = "INVALID_PRODUCT"
)

// Defines values for ProductsListErrorResponseErrorCode.
const (
	ProductsListErrorResponseErrorCodeAUTHORIZATIONFAILURE  ProductsListErrorResponseErrorCode = "AUTHORIZATION_FAILURE"
	ProductsListErrorResponseErrorCodeINTERNALSYSTEMFAILURE ProductsListErrorResponseErrorCode = "INTERNAL_SYSTEM_FAILURE"
	ProductsListErrorResponseErrorCodeINVALIDSUPPLIER       ProductsListErrorResponseErrorCode = "INVALID_SUPPLIER"
)

// Defines values for TicketCodeType.
const (
	AZTEC          TicketCodeType = "AZTEC"
	BARCODECODE128 TicketCodeType = "BARCODE_CODE128"
	BARCODECODE39  TicketCodeType = "BARCODE_CODE39"
	DATAMATRIX     TicketCodeType = "DATA_MATRIX"
	EAN13          TicketCodeType = "EAN_13"
	ITF            TicketCodeType = "ITF"
	QRCODE         TicketCodeType = "QR_CODE"
	TEXT           TicketCodeType = "TEXT"
)

// Defines values for VacanciesByCategoryCategory.
const (
	ADULT            VacanciesByCategoryCategory = "ADULT"
	CHILD            VacanciesByCategoryCategory = "CHILD"
	EUCITIZEN        VacanciesByCategoryCategory = "EU_CITIZEN"
	EUCITIZENSTUDENT VacanciesByCategoryCategory = "EU_CITIZEN_STUDENT"
	INFANT           VacanciesByCategoryCategory = "INFANT"
	MILITARY         VacanciesByCategoryCategory = "MILITARY"
	SENIOR           VacanciesByCategoryCategory = "SENIOR"
	STUDENT          VacanciesByCategoryCategory = "STUDENT"
	YOUTH            VacanciesByCategoryCategory = "YOUTH"
)

// Addon defines model for Addon.
type Addon struct {
	// AddonDescription The description of the addon in your system. Max 50 characters. This field is optional but required and must be unique when multiple addons with the same addonType are present in the response.
	AddonDescription *string `json:"addonDescription,omitempty"`

	// AddonType The Addon Type which is provided during booking.
	AddonType AddonAddonType `json:"addonType"`

	// Currency Code of the currency (ISO 4217), using alphabetic code and three characters in length. Must be a supported currency.
	Currency string `json:"currency"`

	// RetailPrice Integer representation of the smallest unit of the currency. F.e. 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. F.e. 5000 JPY should be price 5000.
	RetailPrice int `json:"retailPrice"`
}

// AddonAddonType The Addon Type which is provided during booking.
type AddonAddonType string

// AddonItem defines model for AddonItem.
type AddonItem struct {
	// AddonDescription The description of the addon in your system. Max 50 characters. This field is optional but required and must be unique when multiple addons with the same addonType are present in the response.
	AddonDescription *string `json:"addonDescription,omitempty"`

	// AddonType The Addon Type which is provided during booking.
	AddonType *AddonItemAddonType `json:"addonType,omitempty"`

	// Count The number of Addon being booked for the specified Addon.
	Count *int `json:"count,omitempty"`

	// RetailPrice Integer representation of the smallest unit of the currency. F.e. 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. F.e. 5000 JPY should be price 5000.
	RetailPrice *int `json:"retailPrice,omitempty"`
}

// AddonItemAddonType The Addon Type which is provided during booking.
type AddonItemAddonType string

// AddonsErrorResponse defines model for AddonsErrorResponse.
type AddonsErrorResponse struct {
	ErrorCode    AddonsErrorResponseErrorCode `json:"errorCode"`
	ErrorMessage *string                      `json:"errorMessage,omitempty"`
}

// AddonsErrorResponseErrorCode defines model for AddonsErrorResponse.ErrorCode.
type AddonsErrorResponseErrorCode string

// AddonsResponse defines model for AddonsResponse.
type AddonsResponse struct {
	// Data A successful data response containing addons list information
	Data GetAddonsSuccessResponse `json:"data"`
}

// Availability defines model for Availability.
type Availability struct {
	// Currency Code of the currency (ISO 4217), using alphabetic code and three characters in length. Must be a supported currency. Example: "EUR"
	Currency *string `json:"currency,omitempty"`

	// CutoffSeconds Cut-off time expressed in seconds for the availability of a specific product (the time until which a product can be booked). This field can be 0
	CutoffSeconds *int `json:"cutoffSeconds,omitempty"`

	// DateTime The date/time of the activity (ISO 8601). Content of the time part depends on the type (see time point vs time period).
	DateTime time.Time `json:"dateTime"`

	// OpeningTimes A list of opening times (from/to pairs) for time period product only. Should be in the format HH:MM
	OpeningTimes *[]struct {
		// FromTime Example: "09:00"
		FromTime *string `json:"fromTime,omitempty"`

		// ToTime Example: "12:00"
		ToTime *string `json:"toTime,omitempty"`
	} `json:"openingTimes,omitempty"`

	// PricesByCategory Object representing the prices of the product
	PricesByCategory *struct {
		// RetailPrices List of retail prices per categories
		RetailPrices []struct {
			// Category The category for which the retail price is being provided.
			Category AvailabilityPricesByCategoryRetailPricesCategory `json:"category"`

			// Price Integer representation of the smallest unit of the currency. Example: 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. Example: 5000 JPY should be price 5000
			Price int `json:"price"`
		} `json:"retailPrices"`
	} `json:"pricesByCategory,omitempty"`

	// ProductId The ID of the requested product in the supplier’s system that this availability refers to.
	ProductId string `json:"productId"`

	// TieredPricesByCategory Object representing the tiered prices of the product
	TieredPricesByCategory *struct {
		// RetailPrices List of tiered prices per categories
		RetailPrices *[]struct {
			// Category The category for which the retail price is being provided.
			Category *AvailabilityTieredPricesByCategoryRetailPricesCategory `json:"category,omitempty"`

			// Tiers List of prices with tiers
			Tiers *[]struct {
				// LowerBound The minimum number of participants for this price tier. Inclusive.
				LowerBound *int `json:"lowerBound,omitempty"`

				// Price Integer representation of the smallest unit of the currency. Example: 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. Example: 5000 JPY should be price 5000
				Price *int `json:"price,omitempty"`

				// UpperBound The maximum number of participants for this price tier. Inclusive.
				UpperBound *int `json:"upperBound"`
			} `json:"tiers,omitempty"`
		} `json:"retailPrices,omitempty"`
	} `json:"tieredPricesByCategory,omitempty"`

	// Vacancies For Individual ticket categories, this is the total number of vacancies across all categories for the requested product at the time slot specified in the dateTime field. If the product has “unlimited” availability please use a large value here. E.g. 5000. For GROUP products, this is the total number of available groups, not the total number of individual vacancies.
	//
	// **Note** - The "vacancies" field has an internal GetYourGuide cap of "5000". If received vacancies exceed 5000 for any DateTimeslot, GetYourGuide will still cap the value to 5000
	Vacancies *int `json:"vacancies,omitempty"`

	// VacanciesByCategory For Individual ticket categories, this is the number of vacancies available for each ticket category for the requested product at the time slot specified in the dateTime field. For GROUP products, this isn't supported.
	VacanciesByCategory *[]VacanciesByCategory `json:"vacanciesByCategory,omitempty"`
	union               json.RawMessage
}

// AvailabilityPricesByCategoryRetailPricesCategory The category for which the retail price is being provided.
type AvailabilityPricesByCategoryRetailPricesCategory string

// AvailabilityTieredPricesByCategoryRetailPricesCategory The category for which the retail price is being provided.
type AvailabilityTieredPricesByCategoryRetailPricesCategory string

// Availability0 defines model for .
type Availability0 = interface{}

// Availability1 defines model for .
type Availability1 = interface{}

// AvailabilityResponse defines model for AvailabilityResponse.
type AvailabilityResponse struct {
	Data struct {
		Availabilities []Availability `json:"availabilities"`
	} `json:"data"`
}

// BookingCancellationRequest defines model for BookingCancellationRequest.
type BookingCancellationRequest struct {
	Data struct {
		// BookingReference An alphanumeric identifier for the booking in the supplier’s system. Maximum length of 25 characters. Example: GYG123JKE453-sf3321C
		BookingReference string `json:"bookingReference"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`.
		ProductId string `json:"productId"`
	} `json:"data"`
}

// BookingItem defines model for BookingItem.
type BookingItem struct {
	// Category The category for which the number of persons is being provided.
	Category Category `json:"category"`

	// Count The number of persons being reserved for the specified category. When bookingItems[].category is GROUP this will always be 1. If we are reserving multiple groups we will add multiple bookingItems.
	Count int `json:"count"`

	// GroupSize Indicates the amount of pax per group, only provided in the context of a bookingItem of category type GROUP. The number of persons being reserved for the specified category. When bookingItems[].category is GROUP it must indicate the number of persons in that group.
	GroupSize *int `json:"groupSize,omitempty"`

	// RetailPrice The basic retail price in the given currency that GetYourGuide charged the customer for one participant of this category during the booking process. This will be sent for all options, regardless of whether Price Over API is enabled. The received retailPrice must never be the reason to fail the booking request. If you observe a wrong price being sent, do not reject the booking and reach out to the Connectivity Support team.
	RetailPrice int `json:"retailPrice"`
}

// BookingRequest defines model for BookingRequest.
type BookingRequest struct {
	Data *struct {
		// AddonItems A list of objects containing information about the addons of this booking.
		AddonItems *[]AddonItem `json:"addonItems,omitempty"`

		// BookingItems A list specifying the number of persons per category in this reservation. The data will be the same as in the corresponding field of the reservation call.
		BookingItems []BookingItem `json:"bookingItems"`

		// Comment Additional information provided by the traveler, e.g., [pick up](https://supplier-support.getyourguide.com/en/support/solutions/articles/15000030542-setting-meeting-point-and-pickup), dietary restrictions, weight, passport, etc. Please note this parameter could contain several thousand characters of unstructured data (free text).<br>
		// Note: this field will always be part of the request. If configured for this product on GetYourGuide it will be filled with the information required, otherwise it will be sent as a string containin only <code>"\n"</code>
		Comment string `json:"comment"`

		// Currency The currency of the retail prices in the request.
		Currency string `json:"currency"`

		// DateTime The date/time of the activity to be reserved (ISO 8601). The date/time of the activity (ISO 8601). Content of the time part is depending on the type (see time point vs time period above).
		DateTime time.Time `json:"dateTime"`

		// GygActivityReference The reference of this activity in GetYourGuide’s system.
		GygActivityReference *string `json:"gygActivityReference,omitempty"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// Language ISO 639-1 code of the language in which the product shall be booked.
		Language *string `json:"language,omitempty"`

		// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`.
		ProductId string `json:"productId"`

		// ReservationReference The identifier for the reservation in the supplier’s system as returned by the reserve call.
		ReservationReference string `json:"reservationReference"`

		// TravelerHotel The traveler’s hotel. This is provided to facilitate pickup where applicable.
		TravelerHotel *string `json:"travelerHotel,omitempty"`

		// Travelers A list of objects containing information about the travelers of this booking. The number of elements does not necessarily match the total indicated by the bookingItems parameter. As default, only the lead traveler is sent, unless set up differently on the Supplier Admin.
		Travelers []Traveler `json:"travelers"`
	} `json:"data,omitempty"`
}

// BookingResponse defines model for BookingResponse.
type BookingResponse struct {
	Data struct {
		// BookingReference An alphanumeric identifier for the booking in the supplier’s system. Maximum length of 25 characters. Example: GYG123JKE453-sf3321C
		BookingReference string   `json:"bookingReference"`
		Tickets          []Ticket `json:"tickets"`
	} `json:"data"`
}

// Category The category for which the number of persons is being provided.
type Category string

// CategoryCollective The category of the ticket. The returned categories must match the type and the count of requested items. Alternatively GetYourGuide accepts 1 (and only 1) `COLLECTIVE` ticket.
type CategoryCollective string

// CategoryConfiguration defines model for CategoryConfiguration.
type CategoryConfiguration struct {
	// AgeFrom The minimum age for a person to fall into this category. If no minimum applies, set to null
	AgeFrom *int `json:"ageFrom"`

	// AgeTo The maximum age for a person to fall into this category. If no maximum applies, set to null
	AgeTo *int `json:"ageTo"`

	// BookingCategory The booking type for this category. The default is STANDARD
	BookingCategory *CategoryConfigurationBookingCategory `json:"bookingCategory"`

	// Category The category associated with this configuration
	Category *string `json:"category,omitempty"`

	// GroupSizeMax The maximum amount of participants in one group
	GroupSizeMax *int `json:"groupSizeMax"`

	// GroupSizeMin The minimum amount of participants in one group
	GroupSizeMin *int `json:"groupSizeMin"`

	// MaxTicketAmount The maximum amount of tickets for this category allowed in one booking
	MaxTicketAmount *int `json:"maxTicketAmount"`

	// MinTicketAmount The minimum amount of tickets for this category allowed in one booking.
	MinTicketAmount *int     `json:"minTicketAmount"`
	Price           *[]Price `json:"price"`
}

// CategoryConfigurationBookingCategory The booking type for this category. The default is STANDARD
type CategoryConfigurationBookingCategory string

// DestinationLocation defines model for DestinationLocation.
type DestinationLocation struct {
	// City The city in which the product is located. Must be in UN/LOCODE NameWoDiacritics format.
	City string `json:"city"`

	// Country The country in which the product is located. Must be in ISO 3166-1 alpha-3 format.
	Country string `json:"country"`
}

// EmptySuccessResponse defines model for EmptySuccessResponse.
type EmptySuccessResponse struct {
	Data *map[string]interface{} `json:"data,omitempty"`
}

// ErrorGroupSizeConstraint defines model for ErrorGroupSizeConstraint.
type ErrorGroupSizeConstraint struct {
	ErrorCode                 ErrorGroupSizeConstraintErrorCode `json:"errorCode"`
	ErrorMessage              *string                           `json:"errorMessage,omitempty"`
	GroupConfiguration        GroupConfiguration                `json:"groupConfiguration"`
	ParticipantsConfiguration ParticipantsConfiguration         `json:"participantsConfiguration"`
}

// ErrorGroupSizeConstraintErrorCode defines model for ErrorGroupSizeConstraint.ErrorCode.
type ErrorGroupSizeConstraintErrorCode string

// ErrorParticipantSizeConstraint defines model for ErrorParticipantSizeConstraint.
type ErrorParticipantSizeConstraint struct {
	ErrorCode                 ErrorParticipantSizeConstraintErrorCode `json:"errorCode"`
	ErrorMessage              *string                                 `json:"errorMessage,omitempty"`
	ParticipantsConfiguration ParticipantsConfiguration               `json:"participantsConfiguration"`
}

// ErrorParticipantSizeConstraintErrorCode defines model for ErrorParticipantSizeConstraint.ErrorCode.
type ErrorParticipantSizeConstraintErrorCode string

// ErrorResponseAvailability defines model for ErrorResponseAvailability.
type ErrorResponseAvailability struct {
	ErrorCode    ErrorResponseAvailabilityErrorCode `json:"errorCode"`
	ErrorMessage *string                            `json:"errorMessage,omitempty"`
}

// ErrorResponseAvailabilityErrorCode defines model for ErrorResponseAvailability.ErrorCode.
type ErrorResponseAvailabilityErrorCode string

// ErrorResponseBooking defines model for ErrorResponseBooking.
type ErrorResponseBooking struct {
	ErrorCode    ErrorResponseBookingErrorCode `json:"errorCode"`
	ErrorMessage *string                       `json:"errorMessage,omitempty"`
}

// ErrorResponseBookingErrorCode defines model for ErrorResponseBooking.ErrorCode.
type ErrorResponseBookingErrorCode string

// ErrorResponseBookingCancellation defines model for ErrorResponseBookingCancellation.
type ErrorResponseBookingCancellation struct {
	ErrorCode    ErrorResponseBookingCancellationErrorCode `json:"errorCode"`
	ErrorMessage *string                                   `json:"errorMessage,omitempty"`
}

// ErrorResponseBookingCancellationErrorCode defines model for ErrorResponseBookingCancellation.ErrorCode.
type ErrorResponseBookingCancellationErrorCode string

// ErrorResponseReservation defines model for ErrorResponseReservation.
type ErrorResponseReservation struct {
	ErrorCode    ErrorResponseReservationErrorCode `json:"errorCode"`
	ErrorMessage *string                           `json:"errorMessage,omitempty"`
}

// ErrorResponseReservationErrorCode defines model for ErrorResponseReservation.ErrorCode.
type ErrorResponseReservationErrorCode string

// ErrorResponseReservationCancellation defines model for ErrorResponseReservationCancellation.
type ErrorResponseReservationCancellation struct {
	ErrorCode    ErrorResponseReservationCancellationErrorCode `json:"errorCode"`
	ErrorMessage *string                                       `json:"errorMessage,omitempty"`
}

// ErrorResponseReservationCancellationErrorCode defines model for ErrorResponseReservationCancellation.ErrorCode.
type ErrorResponseReservationCancellationErrorCode string

// GetAddonsSuccessResponse A successful data response containing addons list information
type GetAddonsSuccessResponse struct {
	// Addons List of all valid addons for a product. If no addons are available for the product, the list should be empty.
	Addons []Addon `json:"addons"`
}

// GetPricingCategoriesSuccessResponse defines model for GetPricingCategoriesSuccessResponse.
type GetPricingCategoriesSuccessResponse struct {
	PricingCategories *[]CategoryConfiguration `json:"pricingCategories,omitempty"`
}

// GroupConfiguration defines model for GroupConfiguration.
type GroupConfiguration struct {
	// Max The maximum number of Groups allowed per booking.
	Max int `json:"max"`
}

// Notification defines model for Notification.
type Notification struct {
	Data NotificationData `json:"data"`
}

// NotificationData defines model for NotificationData.
type NotificationData struct {
	// DateTime The date/time when the notification is sent (ISO 8601).
	DateTime time.Time `json:"dateTime"`

	// Description The description of the notification.
	Description string `json:"description"`

	// IntegrationName The name of the system that the affected product is connected to.
	IntegrationName     string                               `json:"integrationName"`
	NotificationDetails NotificationData_NotificationDetails `json:"notificationDetails"`
	NotificationType    NotificationDataNotificationType     `json:"notificationType"`

	// ProductDetails Details of the affected product.
	ProductDetails NotificationDataProductDetails `json:"productDetails"`

	// SupplierName The supplier name of the affected product.
	SupplierName string `json:"supplierName"`
}

// NotificationData_NotificationDetails defines model for NotificationData.NotificationDetails.
type NotificationData_NotificationDetails struct {
	union json.RawMessage
}

// NotificationDataNotificationType defines model for NotificationData.NotificationType.
type NotificationDataNotificationType string

// NotificationDataProductDetails Details of the affected product.
type NotificationDataProductDetails struct {
	// GygTourOptionId The unique ID of the affected product (tour option) in the GYG’s system.
	GygTourOptionId string `json:"gygTourOptionId"`

	// ProductId The ID of the affected product in the supplier’s system.
	ProductId string `json:"productId"`

	// TourOptionTitle The title of the affected product.
	TourOptionTitle *string `json:"tourOptionTitle,omitempty"`
}

// ParticipantsConfiguration defines model for ParticipantsConfiguration.
type ParticipantsConfiguration struct {
	Max *int `json:"max"`
	Min int  `json:"min"`
}

// Price An object containing price information
type Price struct {
	// Currency Code of the currency (ISO 4217), using alphabetic code and three characters in length. Must be a supported currency.
	Currency *string `json:"currency,omitempty"`

	// Price Integer representation of the smallest unit of the currency. F.e. 10.00 Euro should be 1000. Following currencies are exception - JPY, CLP, KRW, VND. For these currencies we expect the exact retail price. F.e. 5000 JPY should be price 5000
	Price *int `json:"price,omitempty"`

	// PriceType The type of the price
	PriceType *PricePriceType `json:"priceType,omitempty"`
}

// PricePriceType The type of the price
type PricePriceType string

// PricingCategoriesResponse defines model for PricingCategoriesResponse.
type PricingCategoriesResponse struct {
	Data GetPricingCategoriesSuccessResponse `json:"data"`
}

// ProductConfiguration defines model for ProductConfiguration.
type ProductConfiguration struct {
	ParticipantsConfiguration *ProductDetailsParticipantsConfiguration `json:"participantsConfiguration,omitempty"`
}

// ProductDeactivationDataDetails The details of the notification, which could be different from one notification type to another. The properties shown below are the details for a specific notification type `PRODUCT_DEACTIVATION`, which is the only notification type GYG sends to the endpoint at the current moment.
type ProductDeactivationDataDetails struct {
	// ActivityStartTime The start date/time of the requested product in the failed request (ISO 8601). The content of the time part depends on the type (see time point vs time period under [General Definitions](/documentation/overview#section/General-Definitions)).
	ActivityStartTime *time.Time `json:"activityStartTime,omitempty"`

	// ActivityTimeZone The local timezone of the affected product.
	ActivityTimeZone *string `json:"activityTimeZone,omitempty"`

	// DeactivationTimestamp The date/time when the product is deacitvated in GYG's system (ISO 8601).
	DeactivationTimestamp *time.Time `json:"deactivationTimestamp,omitempty"`

	// ErrorMessageReceived The error message received from your system to the failed request.
	ErrorMessageReceived *string `json:"errorMessageReceived,omitempty"`

	// ErrorType The error type received from your system in the response to the failed request.
	ErrorType *string `json:"errorType,omitempty"`

	// FailedRequestType The type of failed request that causes the pruduct deactivation.
	FailedRequestType *string `json:"failedRequestType,omitempty"`

	// GygBookingReference The booking reference of the failed request in GYG’s system.
	GygBookingReference *string `json:"gygBookingReference,omitempty"`

	// Travellers The number of participants were reserved for the specified categories in the failed reservation request. Different ticket categories, e.g., adult and child, are separated using commas.
	Travellers *string `json:"travellers,omitempty"`

	// VacanciesReceivedAfterGetAvailability The vacancies were received from your system during the get-availability check after the failed reservation request.
	VacanciesReceivedAfterGetAvailability *string `json:"vacanciesReceivedAfterGetAvailability,omitempty"`
}

// ProductDetailsErrorResponse defines model for ProductDetailsErrorResponse.
type ProductDetailsErrorResponse struct {
	ErrorCode    ProductDetailsErrorResponseErrorCode `json:"errorCode"`
	ErrorMessage *string                              `json:"errorMessage,omitempty"`
}

// ProductDetailsErrorResponseErrorCode defines model for ProductDetailsErrorResponse.ErrorCode.
type ProductDetailsErrorResponseErrorCode string

// ProductDetailsParticipantsConfiguration defines model for ProductDetailsParticipantsConfiguration.
type ProductDetailsParticipantsConfiguration struct {
	Max *int `json:"max"`
	Min *int `json:"min"`
}

// ProductDetailsResponse defines model for ProductDetailsResponse.
type ProductDetailsResponse struct {
	Data ProductDetailsResponseData `json:"data"`
}

// ProductDetailsResponseData defines model for ProductDetailsResponseData.
type ProductDetailsResponseData struct {
	Configuration       *ProductConfiguration `json:"configuration,omitempty"`
	DestinationLocation DestinationLocation   `json:"destinationLocation"`

	// ProductDescription The description of the product on the Partner platform (SRS). Must be maximum 512 characters long.
	ProductDescription *string `json:"productDescription,omitempty"`

	// ProductTitle The name/Title of the product on the Partner platform (SRS). Must be maximum 512 characters long.
	ProductTitle string `json:"productTitle"`

	// SupplierId The Supplier ID of the supplier on the Partner platform (SRS).
	SupplierId string `json:"supplierId"`
}

// ProductsListErrorResponse defines model for ProductsListErrorResponse.
type ProductsListErrorResponse struct {
	ErrorCode    ProductsListErrorResponseErrorCode `json:"errorCode"`
	ErrorMessage *string                            `json:"errorMessage,omitempty"`
}

// ProductsListErrorResponseErrorCode defines model for ProductsListErrorResponse.ErrorCode.
type ProductsListErrorResponseErrorCode string

// ReservationBookingItem defines model for ReservationBookingItem.
type ReservationBookingItem struct {
	// Category The category for which the number of persons is being provided.
	Category Category `json:"category"`

	// Count The number of persons being reserved for the specified category. When bookingItems[].category is GROUP this will always be 1. If we are reserving multiple groups we will add multiple bookingItems.
	Count int `json:"count"`

	// GroupSize Indicates the amount of pax per group, only provided in the context of a bookingItem of category type GROUP. The number of persons being reserved for the specified category. When bookingItems[].category is GROUP it must indicate the number of persons in that group.
	GroupSize *int `json:"groupSize,omitempty"`
}

// ReservationCancellationRequest defines model for ReservationCancellationRequest.
type ReservationCancellationRequest struct {
	Data struct {
		// GygActivityReference The GYG tour option id which is getting cancelled
		GygActivityReference *string `json:"gygActivityReference,omitempty"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// ReservationReference The identifier for the reservation in the supplier’s system as returned by the reserve call.
		ReservationReference string `json:"reservationReference"`
	} `json:"data"`
}

// ReservationRequest defines model for ReservationRequest.
type ReservationRequest struct {
	Data struct {
		// BookingItems A list specifying the number of persons per category in this reservation.
		BookingItems []ReservationBookingItem `json:"bookingItems"`

		// DateTime The date/time of the activity to be reserved (ISO 8601). For the time period products, the time of the activity is always set to `00:00:00` of the requested travel date (see time point vs time period under [General Definitions](/documentation/overview#section/General-Definitions)).
		DateTime time.Time `json:"dateTime"`

		// GygActivityReference The reference of this activity in GetYourGuide’s system.
		GygActivityReference *string `json:"gygActivityReference,omitempty"`

		// GygBookingReference The reference of this booking in GetYourGuide’s system.
		GygBookingReference string `json:"gygBookingReference"`

		// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`.
		ProductId string `json:"productId"`
	} `json:"data"`
}

// ReservationResponse defines model for ReservationResponse.
type ReservationResponse struct {
	Data struct {
		ReservationExpiration *time.Time `json:"reservationExpiration,omitempty"`

		// ReservationReference The identifier for the reservation in the supplier’s system as returned by the reserve call.
		ReservationReference string `json:"reservationReference"`
	} `json:"data"`
}

// SupplierProduct defines model for SupplierProduct.
type SupplierProduct struct {
	// ProductId The ID of the product A on the Partner platform (SRS).
	ProductId string `json:"productId"`

	// ProductTitle The name of the product A on the Partner platform (SRS). Must be maximum 512 characters long.
	ProductTitle string `json:"productTitle"`
}

// SupplierProductsResponse defines model for SupplierProductsResponse.
type SupplierProductsResponse struct {
	Data SupplierProductsResponseData `json:"data"`
}

// SupplierProductsResponseData defines model for SupplierProductsResponseData.
type SupplierProductsResponseData struct {
	Products []SupplierProduct `json:"products"`

	// SupplierId The Supplier ID of the supplier on the Partner platform (SRS).
	SupplierId string `json:"supplierId"`

	// SupplierName The name of the supplier on the Partner platform (SRS). Must be maximum 512 characters long.
	SupplierName *string `json:"supplierName,omitempty"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	// Category The category of the ticket. The returned categories must match the type and the count of requested items. Alternatively GetYourGuide accepts 1 (and only 1) `COLLECTIVE` ticket.
	Category CategoryCollective `json:"category"`

	// TicketCode The ticket code.<br> If the `TicketCodeType` is `BARCODE_CODE39`, `BARCODE_CODE128` or `ITF` the max lenght of the value is 80 characters.<br> If the `TicketCodeType` is `EAN_13` the lenght of the value must be 12 or 13 characters (lower & upper bound).<br> For all the other `TicketCodeType` the max lenght of the value is 512 characters.
	TicketCode string `json:"ticketCode"`

	// TicketCodeType Indicates how the ticket code shall be rendered on the customer’s voucher.
	TicketCodeType TicketCodeType `json:"ticketCodeType"`
}

// TicketCodeType Indicates how the ticket code shall be rendered on the customer’s voucher.
type TicketCodeType string

// Traveler defines model for Traveler.
type Traveler struct {
	// Email Email address of the traveler
	Email string `json:"email"`

	// FirstName First name of the traveler.
	FirstName string `json:"firstName"`

	// LastName Last name of the traveler.
	LastName string `json:"lastName"`

	// PhoneNumber Phone number of the traveler
	PhoneNumber string `json:"phoneNumber"`
}

// VacanciesByCategory defines model for VacanciesByCategory.
type VacanciesByCategory struct {
	// Category The ticket categories for which the availabilities is being provided.
	Category VacanciesByCategoryCategory `json:"category"`

	// Vacancies The number of vacancies available for the ticket Category.
	Vacancies int `json:"vacancies"`
}

// VacanciesByCategoryCategory The ticket categories for which the availabilities is being provided.
type VacanciesByCategoryCategory string

// GetGetAvailabilitiesParams defines parameters for GetGetAvailabilities.
type GetGetAvailabilitiesParams struct {
	// ProductId The ID of the requested product in the supplier’s system. Please avoid using the character `%` in the `productId`, as it is used as an escape character in URL encoding and may cause encoding/decoding failures in query parameters.
	ProductId string `form:"productId" json:"productId"`

	// FromDateTime Marks the start (inclusive) of the requested time period (ISO 8601).
	FromDateTime string `form:"fromDateTime" json:"fromDateTime"`

	// ToDateTime Marks the end (inclusive) of the requested time period (ISO 8601).
	ToDateTime string `form:"toDateTime" json:"toDateTime"`
}

// PostBookJSONRequestBody defines body for PostBook for application/json ContentType.
type PostBookJSONRequestBody = BookingRequest

// PostCancelBookingJSONRequestBody defines body for PostCancelBooking for application/json ContentType.
type PostCancelBookingJSONRequestBody = BookingCancellationRequest

// PostCancelReservationJSONRequestBody defines body for PostCancelReservation for application/json ContentType.
type PostCancelReservationJSONRequestBody = ReservationCancellationRequest

// PostNotifyJSONRequestBody defines body for PostNotify for application/json ContentType.
type PostNotifyJSONRequestBody = Notification

// PostReserveJSONRequestBody defines body for PostReserve for application/json ContentType.
type PostReserveJSONRequestBody = ReservationRequest

// AsAvailability0 returns the union data inside the Availability as a Availability0
func (t Availability) AsAvailability0() (Availability0, error) {
	var body Availability0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAvailability0 overwrites any union data inside the Availability as the provided Availability0
func (t *Availability) FromAvailability0(v Availability0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAvailability0 performs a merge with any union data inside the Availability, using the provided Availability0
func (t *Availability) MergeAvailability0(v Availability0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAvailability1 returns the union data inside the Availability as a Availability1
func (t Availability) AsAvailability1() (Availability1, error) {
	var body Availability1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAvailability1 overwrites any union data inside the Availability as the provided Availability1
func (t *Availability) FromAvailability1(v Availability1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAvailability1 performs a merge with any union data inside the Availability, using the provided Availability1
func (t *Availability) MergeAvailability1(v Availability1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Availability) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Currency != nil {
		object["currency"], err = json.Marshal(t.Currency)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'currency': %w", err)
		}
	}

	if t.CutoffSeconds != nil {
		object["cutoffSeconds"], err = json.Marshal(t.CutoffSeconds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cutoffSeconds': %w", err)
		}
	}

	object["dateTime"], err = json.Marshal(t.DateTime)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'dateTime': %w", err)
	}

	if t.OpeningTimes != nil {
		object["openingTimes"], err = json.Marshal(t.OpeningTimes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'openingTimes': %w", err)
		}
	}

	if t.PricesByCategory != nil {
		object["pricesByCategory"], err = json.Marshal(t.PricesByCategory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pricesByCategory': %w", err)
		}
	}

	object["productId"], err = json.Marshal(t.ProductId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'productId': %w", err)
	}

	if t.TieredPricesByCategory != nil {
		object["tieredPricesByCategory"], err = json.Marshal(t.TieredPricesByCategory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tieredPricesByCategory': %w", err)
		}
	}

	if t.Vacancies != nil {
		object["vacancies"], err = json.Marshal(t.Vacancies)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vacancies': %w", err)
		}
	}

	if t.VacanciesByCategory != nil {
		object["vacanciesByCategory"], err = json.Marshal(t.VacanciesByCategory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vacanciesByCategory': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *Availability) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["currency"]; found {
		err = json.Unmarshal(raw, &t.Currency)
		if err != nil {
			return fmt.Errorf("error reading 'currency': %w", err)
		}
	}

	if raw, found := object["cutoffSeconds"]; found {
		err = json.Unmarshal(raw, &t.CutoffSeconds)
		if err != nil {
			return fmt.Errorf("error reading 'cutoffSeconds': %w", err)
		}
	}

	if raw, found := object["dateTime"]; found {
		err = json.Unmarshal(raw, &t.DateTime)
		if err != nil {
			return fmt.Errorf("error reading 'dateTime': %w", err)
		}
	}

	if raw, found := object["openingTimes"]; found {
		err = json.Unmarshal(raw, &t.OpeningTimes)
		if err != nil {
			return fmt.Errorf("error reading 'openingTimes': %w", err)
		}
	}

	if raw, found := object["pricesByCategory"]; found {
		err = json.Unmarshal(raw, &t.PricesByCategory)
		if err != nil {
			return fmt.Errorf("error reading 'pricesByCategory': %w", err)
		}
	}

	if raw, found := object["productId"]; found {
		err = json.Unmarshal(raw, &t.ProductId)
		if err != nil {
			return fmt.Errorf("error reading 'productId': %w", err)
		}
	}

	if raw, found := object["tieredPricesByCategory"]; found {
		err = json.Unmarshal(raw, &t.TieredPricesByCategory)
		if err != nil {
			return fmt.Errorf("error reading 'tieredPricesByCategory': %w", err)
		}
	}

	if raw, found := object["vacancies"]; found {
		err = json.Unmarshal(raw, &t.Vacancies)
		if err != nil {
			return fmt.Errorf("error reading 'vacancies': %w", err)
		}
	}

	if raw, found := object["vacanciesByCategory"]; found {
		err = json.Unmarshal(raw, &t.VacanciesByCategory)
		if err != nil {
			return fmt.Errorf("error reading 'vacanciesByCategory': %w", err)
		}
	}

	return err
}

// AsProductDeactivationDataDetails returns the union data inside the NotificationData_NotificationDetails as a ProductDeactivationDataDetails
func (t NotificationData_NotificationDetails) AsProductDeactivationDataDetails() (ProductDeactivationDataDetails, error) {
	var body ProductDeactivationDataDetails
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProductDeactivationDataDetails overwrites any union data inside the NotificationData_NotificationDetails as the provided ProductDeactivationDataDetails
func (t *NotificationData_NotificationDetails) FromProductDeactivationDataDetails(v ProductDeactivationDataDetails) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProductDeactivationDataDetails performs a merge with any union data inside the NotificationData_NotificationDetails, using the provided ProductDeactivationDataDetails
func (t *NotificationData_NotificationDetails) MergeProductDeactivationDataDetails(v ProductDeactivationDataDetails) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NotificationData_NotificationDetails) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NotificationData_NotificationDetails) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostBookWithBody request with any body
	PostBookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostBook(ctx context.Context, body PostBookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCancelBookingWithBody request with any body
	PostCancelBookingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCancelBooking(ctx context.Context, body PostCancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCancelReservationWithBody request with any body
	PostCancelReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCancelReservation(ctx context.Context, body PostCancelReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGetAvailabilities request
	GetGetAvailabilities(ctx context.Context, params *GetGetAvailabilitiesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostNotifyWithBody request with any body
	PostNotifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostNotify(ctx context.Context, body PostNotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProductDetails request
	GetProductDetails(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FetchAddons request
	FetchAddons(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPricingCategories request
	GetPricingCategories(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostReserveWithBody request with any body
	PostReserveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostReserve(ctx context.Context, body PostReserveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSupplierProducts request
	GetSupplierProducts(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostBookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBook(ctx context.Context, body PostBookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCancelBookingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCancelBookingRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCancelBooking(ctx context.Context, body PostCancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCancelBookingRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCancelReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCancelReservationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCancelReservation(ctx context.Context, body PostCancelReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCancelReservationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGetAvailabilities(ctx context.Context, params *GetGetAvailabilitiesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGetAvailabilitiesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostNotifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostNotifyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostNotify(ctx context.Context, body PostNotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostNotifyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProductDetails(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProductDetailsRequest(c.Server, productId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FetchAddons(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFetchAddonsRequest(c.Server, productId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPricingCategories(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPricingCategoriesRequest(c.Server, productId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostReserveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostReserveRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostReserve(ctx context.Context, body PostReserveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostReserveRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSupplierProducts(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSupplierProductsRequest(c.Server, supplierId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostBookRequest calls the generic PostBook builder with application/json body
func NewPostBookRequest(server string, body PostBookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostBookRequestWithBody(server, "application/json", bodyReader)
}

// NewPostBookRequestWithBody generates requests for PostBook with any type of body
func NewPostBookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/book/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostCancelBookingRequest calls the generic PostCancelBooking builder with application/json body
func NewPostCancelBookingRequest(server string, body PostCancelBookingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCancelBookingRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCancelBookingRequestWithBody generates requests for PostCancelBooking with any type of body
func NewPostCancelBookingRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/cancel-booking/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostCancelReservationRequest calls the generic PostCancelReservation builder with application/json body
func NewPostCancelReservationRequest(server string, body PostCancelReservationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCancelReservationRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCancelReservationRequestWithBody generates requests for PostCancelReservation with any type of body
func NewPostCancelReservationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/cancel-reservation/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetGetAvailabilitiesRequest generates requests for GetGetAvailabilities
func NewGetGetAvailabilitiesRequest(server string, params *GetGetAvailabilitiesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/get-availabilities/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "productId", runtime.ParamLocationQuery, params.ProductId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fromDateTime", runtime.ParamLocationQuery, params.FromDateTime); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "toDateTime", runtime.ParamLocationQuery, params.ToDateTime); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostNotifyRequest calls the generic PostNotify builder with application/json body
func NewPostNotifyRequest(server string, body PostNotifyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostNotifyRequestWithBody(server, "application/json", bodyReader)
}

// NewPostNotifyRequestWithBody generates requests for PostNotify with any type of body
func NewPostNotifyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/notify/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProductDetailsRequest generates requests for GetProductDetails
func NewGetProductDetailsRequest(server string, productId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "productId", runtime.ParamLocationPath, productId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/products/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFetchAddonsRequest generates requests for FetchAddons
func NewFetchAddonsRequest(server string, productId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "productId", runtime.ParamLocationPath, productId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/products/%s/addons/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPricingCategoriesRequest generates requests for GetPricingCategories
func NewGetPricingCategoriesRequest(server string, productId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "productId", runtime.ParamLocationPath, productId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/products/%s/pricing-categories/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostReserveRequest calls the generic PostReserve builder with application/json body
func NewPostReserveRequest(server string, body PostReserveJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostReserveRequestWithBody(server, "application/json", bodyReader)
}

// NewPostReserveRequestWithBody generates requests for PostReserve with any type of body
func NewPostReserveRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/reserve/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSupplierProductsRequest generates requests for GetSupplierProducts
func NewGetSupplierProductsRequest(server string, supplierId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "supplierId", runtime.ParamLocationPath, supplierId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1/suppliers/%s/products/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostBookWithBodyWithResponse request with any body
	PostBookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBookResponse, error)

	PostBookWithResponse(ctx context.Context, body PostBookJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBookResponse, error)

	// PostCancelBookingWithBodyWithResponse request with any body
	PostCancelBookingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCancelBookingResponse, error)

	PostCancelBookingWithResponse(ctx context.Context, body PostCancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCancelBookingResponse, error)

	// PostCancelReservationWithBodyWithResponse request with any body
	PostCancelReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCancelReservationResponse, error)

	PostCancelReservationWithResponse(ctx context.Context, body PostCancelReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCancelReservationResponse, error)

	// GetGetAvailabilitiesWithResponse request
	GetGetAvailabilitiesWithResponse(ctx context.Context, params *GetGetAvailabilitiesParams, reqEditors ...RequestEditorFn) (*GetGetAvailabilitiesResponse, error)

	// PostNotifyWithBodyWithResponse request with any body
	PostNotifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostNotifyResponse, error)

	PostNotifyWithResponse(ctx context.Context, body PostNotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostNotifyResponse, error)

	// GetProductDetailsWithResponse request
	GetProductDetailsWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*GetProductDetailsResponse, error)

	// FetchAddonsWithResponse request
	FetchAddonsWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*FetchAddonsResponse, error)

	// GetPricingCategoriesWithResponse request
	GetPricingCategoriesWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*GetPricingCategoriesResponse, error)

	// PostReserveWithBodyWithResponse request with any body
	PostReserveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostReserveResponse, error)

	PostReserveWithResponse(ctx context.Context, body PostReserveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostReserveResponse, error)

	// GetSupplierProductsWithResponse request
	GetSupplierProductsWithResponse(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*GetSupplierProductsResponse, error)
}

type PostBookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostBookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostBookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostCancelBookingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostCancelBookingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCancelBookingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostCancelReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostCancelReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCancelReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGetAvailabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r GetGetAvailabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGetAvailabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostNotifyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptySuccessResponse
}

// Status returns HTTPResponse.Status
func (r PostNotifyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostNotifyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProductDetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r GetProductDetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProductDetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FetchAddonsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r FetchAddonsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FetchAddonsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPricingCategoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PricingCategoriesResponse
}

// Status returns HTTPResponse.Status
func (r GetPricingCategoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPricingCategoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostReserveResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r PostReserveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostReserveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSupplierProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r GetSupplierProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSupplierProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostBookWithBodyWithResponse request with arbitrary body returning *PostBookResponse
func (c *ClientWithResponses) PostBookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBookResponse, error) {
	rsp, err := c.PostBookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBookResponse(rsp)
}

func (c *ClientWithResponses) PostBookWithResponse(ctx context.Context, body PostBookJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBookResponse, error) {
	rsp, err := c.PostBook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBookResponse(rsp)
}

// PostCancelBookingWithBodyWithResponse request with arbitrary body returning *PostCancelBookingResponse
func (c *ClientWithResponses) PostCancelBookingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCancelBookingResponse, error) {
	rsp, err := c.PostCancelBookingWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCancelBookingResponse(rsp)
}

func (c *ClientWithResponses) PostCancelBookingWithResponse(ctx context.Context, body PostCancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCancelBookingResponse, error) {
	rsp, err := c.PostCancelBooking(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCancelBookingResponse(rsp)
}

// PostCancelReservationWithBodyWithResponse request with arbitrary body returning *PostCancelReservationResponse
func (c *ClientWithResponses) PostCancelReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCancelReservationResponse, error) {
	rsp, err := c.PostCancelReservationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCancelReservationResponse(rsp)
}

func (c *ClientWithResponses) PostCancelReservationWithResponse(ctx context.Context, body PostCancelReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCancelReservationResponse, error) {
	rsp, err := c.PostCancelReservation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCancelReservationResponse(rsp)
}

// GetGetAvailabilitiesWithResponse request returning *GetGetAvailabilitiesResponse
func (c *ClientWithResponses) GetGetAvailabilitiesWithResponse(ctx context.Context, params *GetGetAvailabilitiesParams, reqEditors ...RequestEditorFn) (*GetGetAvailabilitiesResponse, error) {
	rsp, err := c.GetGetAvailabilities(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGetAvailabilitiesResponse(rsp)
}

// PostNotifyWithBodyWithResponse request with arbitrary body returning *PostNotifyResponse
func (c *ClientWithResponses) PostNotifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostNotifyResponse, error) {
	rsp, err := c.PostNotifyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostNotifyResponse(rsp)
}

func (c *ClientWithResponses) PostNotifyWithResponse(ctx context.Context, body PostNotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostNotifyResponse, error) {
	rsp, err := c.PostNotify(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostNotifyResponse(rsp)
}

// GetProductDetailsWithResponse request returning *GetProductDetailsResponse
func (c *ClientWithResponses) GetProductDetailsWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*GetProductDetailsResponse, error) {
	rsp, err := c.GetProductDetails(ctx, productId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProductDetailsResponse(rsp)
}

// FetchAddonsWithResponse request returning *FetchAddonsResponse
func (c *ClientWithResponses) FetchAddonsWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*FetchAddonsResponse, error) {
	rsp, err := c.FetchAddons(ctx, productId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFetchAddonsResponse(rsp)
}

// GetPricingCategoriesWithResponse request returning *GetPricingCategoriesResponse
func (c *ClientWithResponses) GetPricingCategoriesWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*GetPricingCategoriesResponse, error) {
	rsp, err := c.GetPricingCategories(ctx, productId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPricingCategoriesResponse(rsp)
}

// PostReserveWithBodyWithResponse request with arbitrary body returning *PostReserveResponse
func (c *ClientWithResponses) PostReserveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostReserveResponse, error) {
	rsp, err := c.PostReserveWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostReserveResponse(rsp)
}

func (c *ClientWithResponses) PostReserveWithResponse(ctx context.Context, body PostReserveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostReserveResponse, error) {
	rsp, err := c.PostReserve(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostReserveResponse(rsp)
}

// GetSupplierProductsWithResponse request returning *GetSupplierProductsResponse
func (c *ClientWithResponses) GetSupplierProductsWithResponse(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*GetSupplierProductsResponse, error) {
	rsp, err := c.GetSupplierProducts(ctx, supplierId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSupplierProductsResponse(rsp)
}

// ParsePostBookResponse parses an HTTP response from a PostBookWithResponse call
func ParsePostBookResponse(rsp *http.Response) (*PostBookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostBookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostCancelBookingResponse parses an HTTP response from a PostCancelBookingWithResponse call
func ParsePostCancelBookingResponse(rsp *http.Response) (*PostCancelBookingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCancelBookingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostCancelReservationResponse parses an HTTP response from a PostCancelReservationWithResponse call
func ParsePostCancelReservationResponse(rsp *http.Response) (*PostCancelReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCancelReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetGetAvailabilitiesResponse parses an HTTP response from a GetGetAvailabilitiesWithResponse call
func ParseGetGetAvailabilitiesResponse(rsp *http.Response) (*GetGetAvailabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGetAvailabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostNotifyResponse parses an HTTP response from a PostNotifyWithResponse call
func ParsePostNotifyResponse(rsp *http.Response) (*PostNotifyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostNotifyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptySuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetProductDetailsResponse parses an HTTP response from a GetProductDetailsWithResponse call
func ParseGetProductDetailsResponse(rsp *http.Response) (*GetProductDetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProductDetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFetchAddonsResponse parses an HTTP response from a FetchAddonsWithResponse call
func ParseFetchAddonsResponse(rsp *http.Response) (*FetchAddonsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FetchAddonsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPricingCategoriesResponse parses an HTTP response from a GetPricingCategoriesWithResponse call
func ParseGetPricingCategoriesResponse(rsp *http.Response) (*GetPricingCategoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPricingCategoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PricingCategoriesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostReserveResponse parses an HTTP response from a PostReserveWithResponse call
func ParsePostReserveResponse(rsp *http.Response) (*PostReserveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostReserveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSupplierProductsResponse parses an HTTP response from a GetSupplierProductsWithResponse call
func ParseGetSupplierProductsResponse(rsp *http.Response) (*GetSupplierProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSupplierProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
